import { TextRotationAngleupSharp } from '@mui/icons-material';
const data = {
  props: [
    {
      name: 'Găng tay da nam',
      slug: 'gang-tay-da-nam',
      category: 'Quần áo',
      image: '/images/gloves.png',
      price: '157.000',
      shop: 'Viewshop36',
      rating: 5,
      numReviews: 7,
      sold: 17,
    },
    {
      name: 'Điện thoại Iphone 11',
      slug: 'dien-thoai-iphone-11',
      category: 'Điện tử',
      image: '/images/phone.png',
      price: '13.650.000',
      shop: 'Tiki Trading',
      shopRating: '4.6',
      shopFollows: '378k+',
      shopIcon: '/pdp-images/tikitrading.png',
      shopReviewsNum: '4.4tr',
      rating: 5,
      numReviews: 353,
      sold: '1000+',
    },
    {
      name: 'Găng tay đi xe máy giữ ấm mùa đông cảm ứng điện thoại dành cho nam',
      slug: 'gang-tay-di-xe-may-giu-am-mua-dong-cam-ung-dien-thoai-danh-cho-nam',
      category: 'Quần áo',
      image: '/images/gloves2.png',
      price: '192.000',
      shop: 'Winshop36',
      rating: 5,
      numReviews: 1,
      sold: 11,
    },
    {
      name: 'iPad 10.2 Inch WiFi 64GB (Gen 9) New 2021',
      slug: 'ipad-10-2-inch-wifi-65gb-new-2021',
      category: 'Điện tử',
      image: '/images/ipad.png',
      price: '9.450.000',
      shop: 'TikiTrading',
      rating: 5,
      numReviews: 46,
      sold: 165,
    },
    {
      name: 'Hộp cơm thủy tinh kèm muỗng đũa LocknLock LLG991CL 930ml',
      slug: 'hop-com-thuy-tinh-kem-muong-dua-locknlock-llg991cl-930ml',
      category: 'stuff',
      image: '/images/lunchbox.png',
      price: '157.000',
      shop: 'TikiTrading',
      rating: 5,
      numReviews: 742,
      sold: '1000+',
    },
    {
      name: 'Nước dưỡng làm mềm và trắng da Senka White Beauty Lotion',
      slug: 'nuoc-duong-lam-mem-va-trang-da-senka-white-beauty-lotion',
      category: 'stuff',
      image: '/images/skincare.png',
      price: '189.000',
      shop: 'Senka Official Store',
      rating: 5,
      numReviews: 39,
      sold: 130,
    },
  ],

  products: [
    {
      name: 'Balo công sở, đi làm nam nữ GuBag, dòng balo doanh nhân cao cấp, đẹp xịn, chống nước, chống sốc',
      slug: 'balo-cong-so-di-lam-nam-nu-gubag-dong-balo-doanh-nhanh-cao-cap-dep-xin-chong-nuoc-chong-soc',
      category: 'Balo, túi sách',
      image: '/product-images/balo.webp',
      price: '439.000',
      shop: 'GuBag Official Store',
      shopRating: '4.6',
      shopFollows: '261',
      shopIcon: '/pdp-images/gubag.png',
      shopReviewsNum: '1k',
      discount: '430.000',
      rating: 5,
      numReviews: 95,
      sold: 210,
    },
    {
      name: 'Dây nịch Huy Hoàng da bò vân cá sấu nhiều màu sắc',
      slug: 'day-nich-huy-hoang-da-bo-van-ca-sau-nhieu-mau-sac',
      category: 'Quần áo',
      image: '/product-images/daynich.webp',
      price: '559.000',
      shop: 'HuyHoang Shop',
      shopRating: '4.5',
      shopFollows: '93',
      shopIcon: '/pdp-images/huyhoang.png',
      shopReviewsNum: '908',
      discount: '540.000',
      rating: 3,
      numReviews: 5,
      sold: 20,
    },
    {
      name: 'NHẬP KHẨU USA CHÍNH HÃNG - Viên uống ngừa loãng xương, hỗ trợ sức khỏe xương khớp Solgar Vitamin D3 1000 IU',
      slug: 'nhap-khau-usa-chinh-hang-vien-uong-ngua-loang-xuong',
      category: 'Thực phẩm chức năng',
      image: '/product-images/nhansam.webp',
      price: '461.000',
      shop: 'Solgar Official Store',
      shopRating: '4.7',
      shopFollows: '313',
      shopIcon: '/pdp-images/solgar.png',
      shopReviewsNum: '190',
      discount: '450.000',
      rating: 5,
      numReviews: 13,
      sold: 47,
    },
    {
      name: 'Tay Cầm PlayStation PS4 Sony Dualshock 4 (Màu Xanh Đen) - Hàng Chính Hãng',
      slug: 'tay-cam-playstation-ps4-sony-dualshock-4-mau-xanh-den-hang-chinh-hang',
      category: 'Điện tử',
      image: '/product-images/ps4.webp',
      price: '1.189.000',
      shop: 'Bách Tung PS',
      shopRating: '4.7',
      shopFollows: '240',
      shopIcon: '/pdp-images/bachtung.png',
      shopReviewsNum: '507',
      discount: '1.150.000',
      rating: 5,
      numReviews: 7,
      sold: 15,
    },
    {
      name: 'VGA GIGABYTE GTX 1050 Ti Windforce OC 4G -Hàng chính hãng',
      slug: 'vga-gigabyte-gtx-1050-ti-windforce-oc-4g-hang-chinh-hang',
      category: 'Điện tử',
      image: '/product-images/vga.webp',
      price: '5.500.000',
      shop: 'Bách Tung PS',
      shopRating: '4.7',
      shopFollows: '240',
      shopIcon: '/pdp-images/bachtung.png',
      shopReviewsNum: '507',
      discount: '5.450.000',
      rating: 4,
      numReviews: 5,
      sold: 11,
    },
    {
      name: 'Khẩu Trang 3D (10 chiếc), Khẩu Trang 4D KF94 Họa Tiết Thời Trang, Khung Vòm 4D Chống Trôi Son, Dùng Một Lần',
      slug: 'khau-trang-3d-10-chiec-khau-trang-4d-kf94-hoa-tiet-thoi-trang-khung-vom-4d-chong-troi-son-dung-mot-lan',
      category: 'Quần áo',
      image: '/product-images/khautrang.webp',
      price: '9000',
      shop: 'VSeat',
      shopRating: '4.8',
      shopFollows: '279',
      shopIcon: '/pdp-images/vseat.jpg',
      shopReviewsNum: '481',
      discount: '8000',
      rating: 5,
      numReviews: 101,
      sold: '1000+',
    },
    {
      name: 'Bộ Ga và Vỏ Gối Akemi Uchi Tencel Melville Mont, 5 món',
      slug: 'bo-ga-va-vo-goi-akemi-uchi-tencel-melville-mont-5-mon',
      category: 'stuff',
      image: '/product-images/gagiuong.webp',
      price: '2.006.000',
      shop: 'Akemi Official Store',
      shopRating: '4.7',
      shopFollows: '400',
      shopIcon: '/pdp-images/akemi.png',
      shopReviewsNum: '74',
      discount: '2.000.000',
      rating: 4,
      numReviews: 2,
      sold: 11,
    },
    {
      name: 'Bàn Gấp Học Sinh Thông Minh Gấp Gọn, Bàn Xếp Laptop Đa Năng Có Thể Gấp Gọn Tùy Chỉnh Nhiều Góc Độ. Chất Liệu Trúc Siêu Nhẹ - Hàng Chính Hãng Tamayoko TM02',
      slug: 'ban-gap-hoc-sinh',
      category: 'stuff',
      image: '/product-images/bangap.webp',
      price: '399.000',
      shop: 'Future Store',
      shopRating: '4.6',
      shopFollows: '2.2k',
      shopIcon: '/pdp-images/future.png',
      shopReviewsNum: '19k',
      discount: '300.000',
      rating: 4,
      numReviews: 301,
      sold: 908,
    },
    {
      name: 'Màn Hình Cong 1500R Gaming Gigabyte G27FC 27" FullHD (1920x1080) 1ms 165Hz VA Cong Stereo Speaker (2W x 2) - Hàng Chính Hãng',
      slug: 'man-hinh-cong-1550r-gaming-gigabyte',
      category: 'Điện tử',
      image: '/product-images/manhinh.webp',
      price: '5.390.000',
      shop: 'Vi Tinh Chi Cuong',
      shopRating: '4.7',
      shopFollows: '511',
      shopIcon: '/pdp-images/vitinhchicuong.png',
      shopReviewsNum: '2.1k',
      discount: '5.300.000',
      rating: 4,
      numReviews: 1,
      sold: 4,
    },
    {
      name: 'Điện Thoại iPhone 13 Pro Max 128GB - Hàng Chính Hãng',
      slug: 'dien-thoai-iphone-13-pro-max-128gb-hang-chinh-hang',
      category: 'Điện tử',
      image: '/product-images/iphone13.webp',
      price: '29.990.000',
      shop: 'Tiki Trading',
      shopRating: '4.6',
      shopFollows: '378k+',
      shopIcon: '/pdp-images/tikitrading.png',
      shopReviewsNum: '4.4tr',
      discount: '29.600.000',
      rating: 5,
      numReviews: 514,
      sold: '1000+',
    },
    {
      name: 'Tai Nghe Bluetooth Chụp Tai Sony WH-1000XM4 Hi-Res Noise Canceling - Hàng Chính Hãng',
      slug: 'tai-nghe-bluetooth',
      category: 'Điện tử',
      image: '/product-images/tainghe.webp',
      price: '5.790.000',
      shop: 'Happystores',
      shopRating: '4.6',
      shopFollows: '798',
      shopIcon: '/pdp-images/happystores.png',
      shopReviewsNum: '3.1k',
      discount: '5.600.000',
      rating: 5,
      numReviews: 211,
      sold: 406,
    },
    {
      name: 'Bảng Treo Đồ Nghề Pegboard Cơ Khí SMLIFE WB3 Lưu Trữ Trưng Bày Dụng Cụ Sửa Chữa Thông Minh Dễ Tìm Kiếm',
      slug: 'bang-treo-do-nghe',
      category: 'Dụng cụ cơ khí',
      image: '/product-images/donghe.webp',
      price: '2.169.000',
      shop: 'SMLIFE',
      shopRating: '4.5',
      shopFollows: '850',
      shopIcon: '/pdp-images/smlife.jpg',
      shopReviewsNum: '708',
      discount: '2.100.000',
      rating: 5,
      numReviews: 2,
      sold: 5,
    },
    {
      name: 'Cây Cam Ngọt Của Tôi',
      slug: 'cay-cam-ngot-cua-toi',
      category: 'Sách',
      image: '/product-images/caycamngot.webp',
      price: '77.000',
      shop: 'Tiki Trading',
      shopRating: '4.6',
      shopFollows: '378k+',
      shopIcon: '/pdp-images/tikitrading.png',
      shopReviewsNum: '4.4tr',
      discount: '70.000',
      rating: 5,
      numReviews: 8352,
      sold: '1000+',
    },
    {
      name: 'Bộ Ga và Vỏ Gối Akemi Cotton Select Affinity gồm 5 món',
      slug: 'bo-ga-va-vo-goi-akemi-cotton',
      category: 'Nhà cửa',
      image: '/product-images/gagiuong2.webp',
      price: '1.526.000',
      shop: 'Akemi Official Store',
      shopRating: '4.7',
      shopFollows: '400',
      shopIcon: '/pdp-images/akemi.png',
      shopReviewsNum: '74',
      discount: '1.500.000',
      rating: 5,
      numReviews: 5,
      sold: 17,
    },
    {
      name: 'Nồi áp suất điện đa năng Tefal CY601868 - 6 Lít - 15 chức năng - Hàng chính hãng',
      slug: 'noi-ap-suat-dien-da-nang-tefal',
      category: 'Điện tử',
      image: '/product-images/noiapsuat.webp',
      price: '1.667.000',
      shop: 'Mỏ Vàng HCM',
      shopRating: '4.6',
      shopFollows: '1k+',
      shopIcon: '/pdp-images/movang.png',
      shopReviewsNum: '1k',
      discount: '1.640.000',
      rating: 3,
      numReviews: 1,
      sold: 3,
    },
    {
      name: 'Smart Tivi Sony Full HD 50 inch KDL-50W660G/Z',
      slug: 'smart-tivi-sony',
      category: 'Điện tử',
      image: '/product-images/smarttivi.webp',
      price: '12.288.000',
      shop: 'Tiki Trading',
      shopRating: '4.6',
      shopFollows: '378k+',
      shopIcon: '/pdp-images/tikitrading.png',
      shopReviewsNum: '4.4tr',
      discount: '12.200.000',
      rating: 5,
      numReviews: 68,
      sold: 229,
    },
    {
      name: 'Combo Chảo chiên Tefal Natura B2260295 20cm & Chảo chiên sâu lòng Tefal Natura B2266495 24cm - Dùng được trên bếp gas/ bếp hồng ngoại - Công nghệ báo nhiệt thông minh - Hàng chính hãng',
      slug: 'combo-chao-choen',
      category: 'Gia dụng',
      image: '/product-images/combochao.webp',
      price: '399.000',
      shop: 'Tefal Official Store',
      shopRating: '4.6',
      shopFollows: '19k+',
      shopIcon: '/pdp-images/tefal.png',
      shopReviewsNum: '20k',
      discount: '359.000',
      rating: 5,
      numReviews: 844,
      sold: '1000+',
    },
    {
      name: 'Bộ Cây Lau Nhà Tự Vắt Thông Minh 2 Ngăn Parroti Pro PR01 Cao Cấp - Lau Sạch Khô Nhanh – 3 Miếng Lau Microfiber',
      slug: 'cay-lau-nha',
      category: 'Gia dụng',
      image: '/product-images/caylaunha.webp',
      price: '499.000',
      shop: 'Parroti Store',
      shopRating: '4.8',
      shopFollows: '4.6k+',
      shopIcon: '/pdp-images/parroti.png',
      shopReviewsNum: '10k',
      discount: '399.000',
      rating: 5,
      numReviews: 2789,
      sold: '1000+',
    },
    {
      name: 'Đồng hồ thể thao nam nữ AT111',
      slug: 'dong-ho-the-thao',
      category: 'Điện tử',
      image: '/product-images/donghothethao.webp',
      price: '18.000',
      shop: 'Thien Hoang Store',
      shopRating: '4.1',
      shopFollows: '341',
      shopIcon: '/pdp-images/thienhoang.png',
      shopReviewsNum: '256',
      discount: '15.000',
      rating: 3,
      numReviews: 4,
      sold: 13,
    },
    {
      name: 'Chú Thuật Hồi Chiến: Trường Chuyên Chú Thuật Tokyo - Tập 0',
      slug: 'chu-thuat-hoi-chien',
      category: 'Sách',
      image: '/product-images/chuthuat.webp',
      price: '27.300',
      shop: 'Tiki Trading',
      shopRating: '4.6',
      shopFollows: '378k+',
      shopIcon: '/pdp-images/tikitrading.png',
      shopReviewsNum: '4.4tr',
      discount: '25.000',
      rating: 5,
      numReviews: 617,
      sold: '1000+',
    },
    {
      name: 'Cho Tôi Xin Một Vé Đi Tuổi Thơ (Phiên Bản Đặc Biệt)',
      slug: 'cho-toi-xin-mot-ve-di-tuoi-tho',
      category: 'Sách',
      image: '/product-images/chotoimotve.webp',
      price: '278.500',
      shop: 'Tiki Trading',
      shopRating: '4.6',
      shopFollows: '378k+',
      shopIcon: '/pdp-images/tikitrading.png',
      shopReviewsNum: '4.4tr',
      discount: '260.000',
      rating: 5,
      numReviews: 112,
      sold: 375,
    },
    {
      name: 'Pin Panasonic CR 2032 - Hàng chính hãng',
      slug: 'pin-panasonic-cr-2032',
      category: 'Điện tử',
      image: '/product-images/pin.webp',
      price: '50.000',
      shop: 'Thegioipin88',
      shopRating: '4.7',
      shopFollows: '133',
      shopIcon: '/pdp-images/thegioipin.png',
      shopReviewsNum: '2.3k',
      discount: '45.000',
      rating: 4,
      numReviews: 40,
      sold: 624,
    },
    {
      name: 'Máy Tính Bảng Samsung Galaxy Tab S7 FE LTE T735 (4GB/64GB) - Hàng Chính Hãng',
      slug: 'may-tinh-bang',
      category: 'Điện tử',
      image: '/product-images/tablet.webp',
      price: '10.390.000',
      shop: 'Tiki Trading',
      shopRating: '4.6',
      shopFollows: '378k+',
      shopIcon: '/pdp-images/tikitrading.png',
      shopReviewsNum: '4.4tr',
      discount: '10.200.000',
      rating: 5,
      numReviews: 42,
      sold: 112,
    },
    {
      name: 'Máy Xay Thịt 2 Lưỡi Kép Nonostyle (2L) - Hàng Chính Hãng',
      slug: 'may-xay-tinh',
      category: 'Điện tử',
      image: '/product-images/mayxaythit.webp',
      price: '275.000',
      shop: 'Tiki Trading',
      shopRating: '4.6',
      shopFollows: '378k+',
      shopIcon: '/pdp-images/tikitrading.png',
      shopReviewsNum: '4.4tr',
      discount: '70.000',
      rating: 5,
      numReviews: 1894,
      sold: '1000+',
    },
  ],
  products1: [
    {
      name: 'Đồng hồ thể thao nam nữ AT111',
      slug: 'dong-ho-the-thao',
      category: 'Điện tử',
      image: '/product-images/donghothethao.webp',
      price: '18.000',
      shop: 'Thien Hoang Store',
      shopRating: '4.1',
      shopFollows: '341',
      shopIcon: '/pdp-images/thienhoang.png',
      shopReviewsNum: '256',
      discount: '15.000',
      rating: 3,
      numReviews: 4,
      sold: 13,
    },
    {
      name: 'Chú Thuật Hồi Chiến: Trường Chuyên Chú Thuật Tokyo - Tập 0',
      slug: 'chu-thuat-hoi-chien',
      category: 'Sách',
      image: '/product-images/chuthuat.webp',
      price: '27.300',
      shop: 'Tiki Trading',
      shopRating: '4.6',
      shopFollows: '378k+',
      shopIcon: '/pdp-images/tikitrading.png',
      shopReviewsNum: '4.4tr',
      discount: '25.000',
      rating: 5,
      numReviews: 617,
      sold: '1000+',
    },
    {
      name: 'Cho Tôi Xin Một Vé Đi Tuổi Thơ (Phiên Bản Đặc Biệt)',
      slug: 'cho-toi-xin-mot-ve-di-tuoi-tho',
      category: 'Sách',
      image: '/product-images/chotoimotve.webp',
      price: '278.500',
      shop: 'Tiki Trading',
      shopRating: '4.6',
      shopFollows: '378k+',
      shopIcon: '/pdp-images/tikitrading.png',
      shopReviewsNum: '4.4tr',
      discount: '260.000',
      rating: 5,
      numReviews: 112,
      sold: 375,
    },
    {
      name: 'Pin Panasonic CR 2032 - Hàng chính hãng',
      slug: 'pin-panasonic-cr-2032',
      category: 'Điện tử',
      image: '/product-images/pin.webp',
      price: '50.000',
      shop: 'Thegioipin88',
      shopRating: '4.7',
      shopFollows: '133',
      shopIcon: '/pdp-images/thegioipin.png',
      shopReviewsNum: '2.3k',
      discount: '45.000',
      rating: 4,
      numReviews: 40,
      sold: 624,
    },
    {
      name: 'Máy Tính Bảng Samsung Galaxy Tab S7 FE LTE T735 (4GB/64GB) - Hàng Chính Hãng',
      slug: 'may-tinh-bang',
      category: 'Điện tử',
      image: '/product-images/tablet.webp',
      price: '10.390.000',
      shop: 'Tiki Trading',
      shopRating: '4.6',
      shopFollows: '378k+',
      shopIcon: '/pdp-images/tikitrading.png',
      shopReviewsNum: '4.4tr',
      discount: '10.200.000',
      rating: 5,
      numReviews: 42,
      sold: 112,
    },
    {
      name: 'Máy Xay Thịt 2 Lưỡi Kép Nonostyle (2L) - Hàng Chính Hãng',
      slug: 'may-xay-tinh',
      category: 'Điện tử',
      image: '/product-images/mayxaythit.webp',
      price: '275.000',
      shop: 'Tiki Trading',
      shopRating: '4.6',
      shopFollows: '378k+',
      shopIcon: '/pdp-images/tikitrading.png',
      shopReviewsNum: '4.4tr',
      discount: '70.000',
      rating: 5,
      numReviews: 1894,
      sold: '1000+',
    },
    {
      name: 'Balo công sở, đi làm nam nữ GuBag, dòng balo doanh nhân cao cấp, đẹp xịn, chống nước, chống sốc',
      slug: 'balo-cong-so-di-lam-nam-nu-gubag-dong-balo-doanh-nhanh-cao-cap-dep-xin-chong-nuoc-chong-soc',
      category: 'Balo, túi sách',
      image: '/product-images/balo.webp',
      price: '439.000',
      shop: 'GuBag Official Store',
      shopRating: '4.6',
      shopFollows: '261',
      shopIcon: '/pdp-images/gubag.png',
      shopReviewsNum: '1k',
      discount: '430.000',
      rating: 5,
      numReviews: 95,
      sold: 210,
    },
    {
      name: 'Dây nịch Huy Hoàng da bò vân cá sấu nhiều màu sắc',
      slug: 'day-nich-huy-hoang-da-bo-van-ca-sau-nhieu-mau-sac',
      category: 'Quần áo',
      image: '/product-images/daynich.webp',
      price: '559.000',
      shop: 'HuyHoang Shop',
      shopRating: '4.5',
      shopFollows: '93',
      shopIcon: '/pdp-images/huyhoang.png',
      shopReviewsNum: '908',
      discount: '540.000',
      rating: 3,
      numReviews: 5,
      sold: 20,
    },
    {
      name: 'NHẬP KHẨU USA CHÍNH HÃNG - Viên uống ngừa loãng xương, hỗ trợ sức khỏe xương khớp Solgar Vitamin D3 1000 IU',
      slug: 'nhap-khau-usa-chinh-hang-vien-uong-ngua-loang-xuong',
      category: 'Thực phẩm chức năng',
      image: '/product-images/nhansam.webp',
      price: '461.000',
      shop: 'Solgar Official Store',
      shopRating: '4.7',
      shopFollows: '313',
      shopIcon: '/pdp-images/solgar.png',
      shopReviewsNum: '190',
      discount: '450.000',
      rating: 5,
      numReviews: 13,
      sold: 47,
    },
    {
      name: 'Tay Cầm PlayStation PS4 Sony Dualshock 4 (Màu Xanh Đen) - Hàng Chính Hãng',
      slug: 'tay-cam-playstation-ps4-sony-dualshock-4-mau-xanh-den-hang-chinh-hang',
      category: 'Điện tử',
      image: '/product-images/ps4.webp',
      price: '1.189.000',
      shop: 'Bách Tung PS',
      shopRating: '4.7',
      shopFollows: '240',
      shopIcon: '/pdp-images/bachtung.png',
      shopReviewsNum: '507',
      discount: '1.150.000',
      rating: 5,
      numReviews: 7,
      sold: 15,
    },
    {
      name: 'VGA GIGABYTE GTX 1050 Ti Windforce OC 4G -Hàng chính hãng',
      slug: 'vga-gigabyte-gtx-1050-ti-windforce-oc-4g-hang-chinh-hang',
      category: 'Điện tử',
      image: '/product-images/vga.webp',
      price: '5.500.000',
      shop: 'Bách Tung PS',
      shopRating: '4.7',
      shopFollows: '240',
      shopIcon: '/pdp-images/bachtung.png',
      shopReviewsNum: '507',
      discount: '5.450.000',
      rating: 4,
      numReviews: 5,
      sold: 11,
    },
    {
      name: 'Khẩu Trang 3D (10 chiếc), Khẩu Trang 4D KF94 Họa Tiết Thời Trang, Khung Vòm 4D Chống Trôi Son, Dùng Một Lần',
      slug: 'khau-trang-3d-10-chiec-khau-trang-4d-kf94-hoa-tiet-thoi-trang-khung-vom-4d-chong-troi-son-dung-mot-lan',
      category: 'Quần áo',
      image: '/product-images/khautrang.webp',
      price: '9000',
      shop: 'VSeat',
      shopRating: '4.8',
      shopFollows: '279',
      shopIcon: '/pdp-images/vseat.jpg',
      shopReviewsNum: '481',
      discount: '8000',
      rating: 5,
      numReviews: 101,
      sold: '1000+',
    },
    {
      name: 'Bộ Ga và Vỏ Gối Akemi Uchi Tencel Melville Mont, 5 món',
      slug: 'bo-ga-va-vo-goi-akemi-uchi-tencel-melville-mont-5-mon',
      category: 'stuff',
      image: '/product-images/gagiuong.webp',
      price: '2.006.000',
      shop: 'Akemi Official Store',
      shopRating: '4.7',
      shopFollows: '400',
      shopIcon: '/pdp-images/akemi.png',
      shopReviewsNum: '74',
      discount: '2.000.000',
      rating: 4,
      numReviews: 2,
      sold: 11,
    },
    {
      name: 'Bàn Gấp Học Sinh Thông Minh Gấp Gọn, Bàn Xếp Laptop Đa Năng Có Thể Gấp Gọn Tùy Chỉnh Nhiều Góc Độ. Chất Liệu Trúc Siêu Nhẹ - Hàng Chính Hãng Tamayoko TM02',
      slug: 'ban-gap-hoc-sinh',
      category: 'stuff',
      image: '/product-images/bangap.webp',
      price: '399.000',
      shop: 'Future Store',
      shopRating: '4.6',
      shopFollows: '2.2k',
      shopIcon: '/pdp-images/future.png',
      shopReviewsNum: '19k',
      discount: '300.000',
      rating: 4,
      numReviews: 301,
      sold: 908,
    },
    {
      name: 'Màn Hình Cong 1500R Gaming Gigabyte G27FC 27" FullHD (1920x1080) 1ms 165Hz VA Cong Stereo Speaker (2W x 2) - Hàng Chính Hãng',
      slug: 'man-hinh-cong-1550r-gaming-gigabyte',
      category: 'Điện tử',
      image: '/product-images/manhinh.webp',
      price: '5.390.000',
      shop: 'Vi Tinh Chi Cuong',
      shopRating: '4.7',
      shopFollows: '511',
      shopIcon: '/pdp-images/vitinhchicuong.png',
      shopReviewsNum: '2.1k',
      discount: '5.300.000',
      rating: 4,
      numReviews: 1,
      sold: 4,
    },
    {
      name: 'Điện Thoại iPhone 13 Pro Max 128GB - Hàng Chính Hãng',
      slug: 'dien-thoai-iphone-13-pro-max-128gb-hang-chinh-hang',
      category: 'Điện tử',
      image: '/product-images/iphone13.webp',
      price: '29.990.000',
      shop: 'Tiki Trading',
      shopRating: '4.6',
      shopFollows: '378k+',
      shopIcon: '/pdp-images/tikitrading.png',
      shopReviewsNum: '4.4tr',
      discount: '29.600.000',
      rating: 5,
      numReviews: 514,
      sold: '1000+',
    },
    {
      name: 'Tai Nghe Bluetooth Chụp Tai Sony WH-1000XM4 Hi-Res Noise Canceling - Hàng Chính Hãng',
      slug: 'tai-nghe-bluetooth',
      category: 'Điện tử',
      image: '/product-images/tainghe.webp',
      price: '5.790.000',
      shop: 'Happystores',
      shopRating: '4.6',
      shopFollows: '798',
      shopIcon: '/pdp-images/happystores.png',
      shopReviewsNum: '3.1k',
      discount: '5.600.000',
      rating: 5,
      numReviews: 211,
      sold: 406,
    },
    {
      name: 'Bảng Treo Đồ Nghề Pegboard Cơ Khí SMLIFE WB3 Lưu Trữ Trưng Bày Dụng Cụ Sửa Chữa Thông Minh Dễ Tìm Kiếm',
      slug: 'bang-treo-do-nghe',
      category: 'Dụng cụ cơ khí',
      image: '/product-images/donghe.webp',
      price: '2.169.000',
      shop: 'SMLIFE',
      shopRating: '4.5',
      shopFollows: '850',
      shopIcon: '/pdp-images/smlife.jpg',
      shopReviewsNum: '708',
      discount: '2.100.000',
      rating: 5,
      numReviews: 2,
      sold: 5,
    },
    {
      name: 'Cây Cam Ngọt Của Tôi',
      slug: 'cay-cam-ngot-cua-toi',
      category: 'Sách',
      image: '/product-images/caycamngot.webp',
      price: '77.000',
      shop: 'Tiki Trading',
      shopRating: '4.6',
      shopFollows: '378k+',
      shopIcon: '/pdp-images/tikitrading.png',
      shopReviewsNum: '4.4tr',
      discount: '70.000',
      rating: 5,
      numReviews: 8352,
      sold: '1000+',
    },
    {
      name: 'Bộ Ga và Vỏ Gối Akemi Cotton Select Affinity gồm 5 món',
      slug: 'bo-ga-va-vo-goi-akemi-cotton',
      category: 'Nhà cửa',
      image: '/product-images/gagiuong2.webp',
      price: '1.526.000',
      shop: 'Akemi Official Store',
      shopRating: '4.7',
      shopFollows: '400',
      shopIcon: '/pdp-images/akemi.png',
      shopReviewsNum: '74',
      discount: '1.500.000',
      rating: 5,
      numReviews: 5,
      sold: 17,
    },
    {
      name: 'Nồi áp suất điện đa năng Tefal CY601868 - 6 Lít - 15 chức năng - Hàng chính hãng',
      slug: 'noi-ap-suat-dien-da-nang-tefal',
      category: 'Điện tử',
      image: '/product-images/noiapsuat.webp',
      price: '1.667.000',
      shop: 'Mỏ Vàng HCM',
      shopRating: '4.6',
      shopFollows: '1k+',
      shopIcon: '/pdp-images/movang.png',
      shopReviewsNum: '1k',
      discount: '1.640.000',
      rating: 3,
      numReviews: 1,
      sold: 3,
    },
    {
      name: 'Smart Tivi Sony Full HD 50 inch KDL-50W660G/Z',
      slug: 'smart-tivi-sony',
      category: 'Điện tử',
      image: '/product-images/smarttivi.webp',
      price: '12.288.000',
      shop: 'Tiki Trading',
      shopRating: '4.6',
      shopFollows: '378k+',
      shopIcon: '/pdp-images/tikitrading.png',
      shopReviewsNum: '4.4tr',
      discount: '12.200.000',
      rating: 5,
      numReviews: 68,
      sold: 229,
    },
    {
      name: 'Combo Chảo chiên Tefal Natura B2260295 20cm & Chảo chiên sâu lòng Tefal Natura B2266495 24cm - Dùng được trên bếp gas/ bếp hồng ngoại - Công nghệ báo nhiệt thông minh - Hàng chính hãng',
      slug: 'combo-chao-choen',
      category: 'Gia dụng',
      image: '/product-images/combochao.webp',
      price: '399.000',
      shop: 'Tefal Official Store',
      shopRating: '4.6',
      shopFollows: '19k+',
      shopIcon: '/pdp-images/tefal.png',
      shopReviewsNum: '20k',
      discount: '359.000',
      rating: 5,
      numReviews: 844,
      sold: '1000+',
    },
    {
      name: 'Bộ Cây Lau Nhà Tự Vắt Thông Minh 2 Ngăn Parroti Pro PR01 Cao Cấp - Lau Sạch Khô Nhanh – 3 Miếng Lau Microfiber',
      slug: 'cay-lau-nha',
      category: 'Gia dụng',
      image: '/product-images/caylaunha.webp',
      price: '499.000',
      shop: 'Parroti Store',
      shopRating: '4.8',
      shopFollows: '4.6k+',
      shopIcon: '/pdp-images/parroti.png',
      shopReviewsNum: '10k',
      discount: '399.000',
      rating: 5,
      numReviews: 2789,
      sold: '1000+',
    },
  ],
  products2: [
    {
      name: 'Bộ Ga và Vỏ Gối Akemi Uchi Tencel Melville Mont, 5 món',
      slug: 'bo-ga-va-vo-goi-akemi-uchi-tencel-melville-mont-5-mon',
      category: 'stuff',
      image: '/product-images/gagiuong.webp',
      price: '2.006.000',
      shop: 'Akemi Official Store',
      shopRating: '4.7',
      shopFollows: '400',
      shopIcon: '/pdp-images/akemi.png',
      shopReviewsNum: '74',
      discount: '2.000.000',
      rating: 4,
      numReviews: 2,
      sold: 11,
    },
    {
      name: 'Bàn Gấp Học Sinh Thông Minh Gấp Gọn, Bàn Xếp Laptop Đa Năng Có Thể Gấp Gọn Tùy Chỉnh Nhiều Góc Độ. Chất Liệu Trúc Siêu Nhẹ - Hàng Chính Hãng Tamayoko TM02',
      slug: 'ban-gap-hoc-sinh',
      category: 'stuff',
      image: '/product-images/bangap.webp',
      price: '399.000',
      shop: 'Future Store',
      shopRating: '4.6',
      shopFollows: '2.2k',
      shopIcon: '/pdp-images/future.png',
      shopReviewsNum: '19k',
      discount: '300.000',
      rating: 4,
      numReviews: 301,
      sold: 908,
    },
    {
      name: 'Màn Hình Cong 1500R Gaming Gigabyte G27FC 27" FullHD (1920x1080) 1ms 165Hz VA Cong Stereo Speaker (2W x 2) - Hàng Chính Hãng',
      slug: 'man-hinh-cong-1550r-gaming-gigabyte',
      category: 'Điện tử',
      image: '/product-images/manhinh.webp',
      price: '5.390.000',
      shop: 'Vi Tinh Chi Cuong',
      shopRating: '4.7',
      shopFollows: '511',
      shopIcon: '/pdp-images/vitinhchicuong.png',
      shopReviewsNum: '2.1k',
      discount: '5.300.000',
      rating: 4,
      numReviews: 1,
      sold: 4,
    },
    {
      name: 'Điện Thoại iPhone 13 Pro Max 128GB - Hàng Chính Hãng',
      slug: 'dien-thoai-iphone-13-pro-max-128gb-hang-chinh-hang',
      category: 'Điện tử',
      image: '/product-images/iphone13.webp',
      price: '29.990.000',
      shop: 'Tiki Trading',
      shopRating: '4.6',
      shopFollows: '378k+',
      shopIcon: '/pdp-images/tikitrading.png',
      shopReviewsNum: '4.4tr',
      discount: '29.600.000',
      rating: 5,
      numReviews: 514,
      sold: '1000+',
    },
    {
      name: 'Tai Nghe Bluetooth Chụp Tai Sony WH-1000XM4 Hi-Res Noise Canceling - Hàng Chính Hãng',
      slug: 'tai-nghe-bluetooth',
      category: 'Điện tử',
      image: '/product-images/tainghe.webp',
      price: '5.790.000',
      shop: 'Happystores',
      shopRating: '4.6',
      shopFollows: '798',
      shopIcon: '/pdp-images/happystores.png',
      shopReviewsNum: '3.1k',
      discount: '5.600.000',
      rating: 5,
      numReviews: 211,
      sold: 406,
    },
    {
      name: 'Bảng Treo Đồ Nghề Pegboard Cơ Khí SMLIFE WB3 Lưu Trữ Trưng Bày Dụng Cụ Sửa Chữa Thông Minh Dễ Tìm Kiếm',
      slug: 'bang-treo-do-nghe',
      category: 'Dụng cụ cơ khí',
      image: '/product-images/donghe.webp',
      price: '2.169.000',
      shop: 'SMLIFE',
      shopRating: '4.5',
      shopFollows: '850',
      shopIcon: '/pdp-images/smlife.jpg',
      shopReviewsNum: '708',
      discount: '2.100.000',
      rating: 5,
      numReviews: 2,
      sold: 5,
    },
    {
      name: 'Balo công sở, đi làm nam nữ GuBag, dòng balo doanh nhân cao cấp, đẹp xịn, chống nước, chống sốc',
      slug: 'balo-cong-so-di-lam-nam-nu-gubag-dong-balo-doanh-nhanh-cao-cap-dep-xin-chong-nuoc-chong-soc',
      category: 'Balo, túi sách',
      image: '/product-images/balo.webp',
      price: '439.000',
      shop: 'GuBag Official Store',
      shopRating: '4.6',
      shopFollows: '261',
      shopIcon: '/pdp-images/gubag.png',
      shopReviewsNum: '1k',
      discount: '430.000',
      rating: 5,
      numReviews: 95,
      sold: 210,
    },
    {
      name: 'Dây nịch Huy Hoàng da bò vân cá sấu nhiều màu sắc',
      slug: 'day-nich-huy-hoang-da-bo-van-ca-sau-nhieu-mau-sac',
      category: 'Quần áo',
      image: '/product-images/daynich.webp',
      price: '559.000',
      shop: 'HuyHoang Shop',
      shopRating: '4.5',
      shopFollows: '93',
      shopIcon: '/pdp-images/huyhoang.png',
      shopReviewsNum: '908',
      discount: '540.000',
      rating: 3,
      numReviews: 5,
      sold: 20,
    },
    {
      name: 'NHẬP KHẨU USA CHÍNH HÃNG - Viên uống ngừa loãng xương, hỗ trợ sức khỏe xương khớp Solgar Vitamin D3 1000 IU',
      slug: 'nhap-khau-usa-chinh-hang-vien-uong-ngua-loang-xuong',
      category: 'Thực phẩm chức năng',
      image: '/product-images/nhansam.webp',
      price: '461.000',
      shop: 'Solgar Official Store',
      shopRating: '4.7',
      shopFollows: '313',
      shopIcon: '/pdp-images/solgar.png',
      shopReviewsNum: '190',
      discount: '450.000',
      rating: 5,
      numReviews: 13,
      sold: 47,
    },
    {
      name: 'Tay Cầm PlayStation PS4 Sony Dualshock 4 (Màu Xanh Đen) - Hàng Chính Hãng',
      slug: 'tay-cam-playstation-ps4-sony-dualshock-4-mau-xanh-den-hang-chinh-hang',
      category: 'Điện tử',
      image: '/product-images/ps4.webp',
      price: '1.189.000',
      shop: 'Bách Tung PS',
      shopRating: '4.7',
      shopFollows: '240',
      shopIcon: '/pdp-images/bachtung.png',
      shopReviewsNum: '507',
      discount: '1.150.000',
      rating: 5,
      numReviews: 7,
      sold: 15,
    },
    {
      name: 'VGA GIGABYTE GTX 1050 Ti Windforce OC 4G -Hàng chính hãng',
      slug: 'vga-gigabyte-gtx-1050-ti-windforce-oc-4g-hang-chinh-hang',
      category: 'Điện tử',
      image: '/product-images/vga.webp',
      price: '5.500.000',
      shop: 'Bách Tung PS',
      shopRating: '4.7',
      shopFollows: '240',
      shopIcon: '/pdp-images/bachtung.png',
      shopReviewsNum: '507',
      discount: '5.450.000',
      rating: 4,
      numReviews: 5,
      sold: 11,
    },
    {
      name: 'Khẩu Trang 3D (10 chiếc), Khẩu Trang 4D KF94 Họa Tiết Thời Trang, Khung Vòm 4D Chống Trôi Son, Dùng Một Lần',
      slug: 'khau-trang-3d-10-chiec-khau-trang-4d-kf94-hoa-tiet-thoi-trang-khung-vom-4d-chong-troi-son-dung-mot-lan',
      category: 'Quần áo',
      image: '/product-images/khautrang.webp',
      price: '9000',
      shop: 'VSeat',
      shopRating: '4.8',
      shopFollows: '279',
      shopIcon: '/pdp-images/vseat.jpg',
      shopReviewsNum: '481',
      discount: '8000',
      rating: 5,
      numReviews: 101,
      sold: '1000+',
    },
    {
      name: 'Đồng hồ thể thao nam nữ AT111',
      slug: 'dong-ho-the-thao',
      category: 'Điện tử',
      image: '/product-images/donghothethao.webp',
      price: '18.000',
      shop: 'Thien Hoang Store',
      shopRating: '4.1',
      shopFollows: '341',
      shopIcon: '/pdp-images/thienhoang.png',
      shopReviewsNum: '256',
      discount: '15.000',
      rating: 3,
      numReviews: 4,
      sold: 13,
    },
    {
      name: 'Chú Thuật Hồi Chiến: Trường Chuyên Chú Thuật Tokyo - Tập 0',
      slug: 'chu-thuat-hoi-chien',
      category: 'Sách',
      image: '/product-images/chuthuat.webp',
      price: '27.300',
      shop: 'Tiki Trading',
      shopRating: '4.6',
      shopFollows: '378k+',
      shopIcon: '/pdp-images/tikitrading.png',
      shopReviewsNum: '4.4tr',
      discount: '25.000',
      rating: 5,
      numReviews: 617,
      sold: '1000+',
    },
    {
      name: 'Cho Tôi Xin Một Vé Đi Tuổi Thơ (Phiên Bản Đặc Biệt)',
      slug: 'cho-toi-xin-mot-ve-di-tuoi-tho',
      category: 'Sách',
      image: '/product-images/chotoimotve.webp',
      price: '278.500',
      shop: 'Tiki Trading',
      shopRating: '4.6',
      shopFollows: '378k+',
      shopIcon: '/pdp-images/tikitrading.png',
      shopReviewsNum: '4.4tr',
      discount: '260.000',
      rating: 5,
      numReviews: 112,
      sold: 375,
    },
    {
      name: 'Pin Panasonic CR 2032 - Hàng chính hãng',
      slug: 'pin-panasonic-cr-2032',
      category: 'Điện tử',
      image: '/product-images/pin.webp',
      price: '50.000',
      shop: 'Thegioipin88',
      shopRating: '4.7',
      shopFollows: '133',
      shopIcon: '/pdp-images/thegioipin.png',
      shopReviewsNum: '2.3k',
      discount: '45.000',
      rating: 4,
      numReviews: 40,
      sold: 624,
    },
    {
      name: 'Máy Tính Bảng Samsung Galaxy Tab S7 FE LTE T735 (4GB/64GB) - Hàng Chính Hãng',
      slug: 'may-tinh-bang',
      category: 'Điện tử',
      image: '/product-images/tablet.webp',
      price: '10.390.000',
      shop: 'Tiki Trading',
      shopRating: '4.6',
      shopFollows: '378k+',
      shopIcon: '/pdp-images/tikitrading.png',
      shopReviewsNum: '4.4tr',
      discount: '10.200.000',
      rating: 5,
      numReviews: 42,
      sold: 112,
    },
    {
      name: 'Máy Xay Thịt 2 Lưỡi Kép Nonostyle (2L) - Hàng Chính Hãng',
      slug: 'may-xay-tinh',
      category: 'Điện tử',
      image: '/product-images/mayxaythit.webp',
      price: '275.000',
      shop: 'Tiki Trading',
      shopRating: '4.6',
      shopFollows: '378k+',
      shopIcon: '/pdp-images/tikitrading.png',
      shopReviewsNum: '4.4tr',
      discount: '70.000',
      rating: 5,
      numReviews: 1894,
      sold: '1000+',
    },
    {
      name: 'Cây Cam Ngọt Của Tôi',
      slug: 'cay-cam-ngot-cua-toi',
      category: 'Sách',
      image: '/product-images/caycamngot.webp',
      price: '77.000',
      shop: 'Tiki Trading',
      shopRating: '4.6',
      shopFollows: '378k+',
      shopIcon: '/pdp-images/tikitrading.png',
      shopReviewsNum: '4.4tr',
      discount: '70.000',
      rating: 5,
      numReviews: 8352,
      sold: '1000+',
    },
    {
      name: 'Bộ Ga và Vỏ Gối Akemi Cotton Select Affinity gồm 5 món',
      slug: 'bo-ga-va-vo-goi-akemi-cotton',
      category: 'Nhà cửa',
      image: '/product-images/gagiuong2.webp',
      price: '1.526.000',
      shop: 'Akemi Official Store',
      shopRating: '4.7',
      shopFollows: '400',
      shopIcon: '/pdp-images/akemi.png',
      shopReviewsNum: '74',
      discount: '1.500.000',
      rating: 5,
      numReviews: 5,
      sold: 17,
    },
    {
      name: 'Nồi áp suất điện đa năng Tefal CY601868 - 6 Lít - 15 chức năng - Hàng chính hãng',
      slug: 'noi-ap-suat-dien-da-nang-tefal',
      category: 'Điện tử',
      image: '/product-images/noiapsuat.webp',
      price: '1.667.000',
      shop: 'Mỏ Vàng HCM',
      shopRating: '4.6',
      shopFollows: '1k+',
      shopIcon: '/pdp-images/movang.png',
      shopReviewsNum: '1k',
      discount: '1.640.000',
      rating: 3,
      numReviews: 1,
      sold: 3,
    },
    {
      name: 'Smart Tivi Sony Full HD 50 inch KDL-50W660G/Z',
      slug: 'smart-tivi-sony',
      category: 'Điện tử',
      image: '/product-images/smarttivi.webp',
      price: '12.288.000',
      shop: 'Tiki Trading',
      shopRating: '4.6',
      shopFollows: '378k+',
      shopIcon: '/pdp-images/tikitrading.png',
      shopReviewsNum: '4.4tr',
      discount: '12.200.000',
      rating: 5,
      numReviews: 68,
      sold: 229,
    },
    {
      name: 'Combo Chảo chiên Tefal Natura B2260295 20cm & Chảo chiên sâu lòng Tefal Natura B2266495 24cm - Dùng được trên bếp gas/ bếp hồng ngoại - Công nghệ báo nhiệt thông minh - Hàng chính hãng',
      slug: 'combo-chao-choen',
      category: 'Gia dụng',
      image: '/product-images/combochao.webp',
      price: '399.000',
      shop: 'Tefal Official Store',
      shopRating: '4.6',
      shopFollows: '19k+',
      shopIcon: '/pdp-images/tefal.png',
      shopReviewsNum: '20k',
      discount: '359.000',
      rating: 5,
      numReviews: 844,
      sold: '1000+',
    },
    {
      name: 'Bộ Cây Lau Nhà Tự Vắt Thông Minh 2 Ngăn Parroti Pro PR01 Cao Cấp - Lau Sạch Khô Nhanh – 3 Miếng Lau Microfiber',
      slug: 'cay-lau-nha',
      category: 'Gia dụng',
      image: '/product-images/caylaunha.webp',
      price: '499.000',
      shop: 'Parroti Store',
      shopRating: '4.8',
      shopFollows: '4.6k+',
      shopIcon: '/pdp-images/parroti.png',
      shopReviewsNum: '10k',
      discount: '399.000',
      rating: 5,
      numReviews: 2789,
      sold: '1000+',
    },
  ],
  products3: [
    {
      name: 'Cây Cam Ngọt Của Tôi',
      slug: 'cay-cam-ngot-cua-toi',
      category: 'Sách',
      image: '/product-images/caycamngot.webp',
      price: '77.000',
      shop: 'Tiki Trading',
      shopRating: '4.6',
      shopFollows: '378k+',
      shopIcon: '/pdp-images/tikitrading.png',
      shopReviewsNum: '4.4tr',
      discount: '70.000',
      rating: 5,
      numReviews: 8352,
      sold: '1000+',
    },
    {
      name: 'Bộ Ga và Vỏ Gối Akemi Cotton Select Affinity gồm 5 món',
      slug: 'bo-ga-va-vo-goi-akemi-cotton',
      category: 'Nhà cửa',
      image: '/product-images/gagiuong2.webp',
      price: '1.526.000',
      shop: 'Akemi Official Store',
      shopRating: '4.7',
      shopFollows: '400',
      shopIcon: '/pdp-images/akemi.png',
      shopReviewsNum: '74',
      discount: '1.500.000',
      rating: 5,
      numReviews: 5,
      sold: 17,
    },
    {
      name: 'Nồi áp suất điện đa năng Tefal CY601868 - 6 Lít - 15 chức năng - Hàng chính hãng',
      slug: 'noi-ap-suat-dien-da-nang-tefal',
      category: 'Điện tử',
      image: '/product-images/noiapsuat.webp',
      price: '1.667.000',
      shop: 'Mỏ Vàng HCM',
      shopRating: '4.6',
      shopFollows: '1k+',
      shopIcon: '/pdp-images/movang.png',
      shopReviewsNum: '1k',
      discount: '1.640.000',
      rating: 3,
      numReviews: 1,
      sold: 3,
    },
    {
      name: 'Smart Tivi Sony Full HD 50 inch KDL-50W660G/Z',
      slug: 'smart-tivi-sony',
      category: 'Điện tử',
      image: '/product-images/smarttivi.webp',
      price: '12.288.000',
      shop: 'Tiki Trading',
      shopRating: '4.6',
      shopFollows: '378k+',
      shopIcon: '/pdp-images/tikitrading.png',
      shopReviewsNum: '4.4tr',
      discount: '12.200.000',
      rating: 5,
      numReviews: 68,
      sold: 229,
    },
    {
      name: 'Combo Chảo chiên Tefal Natura B2260295 20cm & Chảo chiên sâu lòng Tefal Natura B2266495 24cm - Dùng được trên bếp gas/ bếp hồng ngoại - Công nghệ báo nhiệt thông minh - Hàng chính hãng',
      slug: 'combo-chao-choen',
      category: 'Gia dụng',
      image: '/product-images/combochao.webp',
      price: '399.000',
      shop: 'Tefal Official Store',
      shopRating: '4.6',
      shopFollows: '19k+',
      shopIcon: '/pdp-images/tefal.png',
      shopReviewsNum: '20k',
      discount: '359.000',
      rating: 5,
      numReviews: 844,
      sold: '1000+',
    },
    {
      name: 'Bộ Cây Lau Nhà Tự Vắt Thông Minh 2 Ngăn Parroti Pro PR01 Cao Cấp - Lau Sạch Khô Nhanh – 3 Miếng Lau Microfiber',
      slug: 'cay-lau-nha',
      category: 'Gia dụng',
      image: '/product-images/caylaunha.webp',
      price: '499.000',
      shop: 'Parroti Store',
      shopRating: '4.8',
      shopFollows: '4.6k+',
      shopIcon: '/pdp-images/parroti.png',
      shopReviewsNum: '10k',
      discount: '399.000',
      rating: 5,
      numReviews: 2789,
      sold: '1000+',
    },
    {
      name: 'Đồng hồ thể thao nam nữ AT111',
      slug: 'dong-ho-the-thao',
      category: 'Điện tử',
      image: '/product-images/donghothethao.webp',
      price: '18.000',
      shop: 'Thien Hoang Store',
      shopRating: '4.1',
      shopFollows: '341',
      shopIcon: '/pdp-images/thienhoang.png',
      shopReviewsNum: '256',
      discount: '15.000',
      rating: 3,
      numReviews: 4,
      sold: 13,
    },
    {
      name: 'Chú Thuật Hồi Chiến: Trường Chuyên Chú Thuật Tokyo - Tập 0',
      slug: 'chu-thuat-hoi-chien',
      category: 'Sách',
      image: '/product-images/chuthuat.webp',
      price: '27.300',
      shop: 'Tiki Trading',
      shopRating: '4.6',
      shopFollows: '378k+',
      shopIcon: '/pdp-images/tikitrading.png',
      shopReviewsNum: '4.4tr',
      discount: '25.000',
      rating: 5,
      numReviews: 617,
      sold: '1000+',
    },
    {
      name: 'Cho Tôi Xin Một Vé Đi Tuổi Thơ (Phiên Bản Đặc Biệt)',
      slug: 'cho-toi-xin-mot-ve-di-tuoi-tho',
      category: 'Sách',
      image: '/product-images/chotoimotve.webp',
      price: '278.500',
      shop: 'Tiki Trading',
      shopRating: '4.6',
      shopFollows: '378k+',
      shopIcon: '/pdp-images/tikitrading.png',
      shopReviewsNum: '4.4tr',
      discount: '260.000',
      rating: 5,
      numReviews: 112,
      sold: 375,
    },
    {
      name: 'Pin Panasonic CR 2032 - Hàng chính hãng',
      slug: 'pin-panasonic-cr-2032',
      category: 'Điện tử',
      image: '/product-images/pin.webp',
      price: '50.000',
      shop: 'Thegioipin88',
      shopRating: '4.7',
      shopFollows: '133',
      shopIcon: '/pdp-images/thegioipin.png',
      shopReviewsNum: '2.3k',
      discount: '45.000',
      rating: 4,
      numReviews: 40,
      sold: 624,
    },
    {
      name: 'Máy Tính Bảng Samsung Galaxy Tab S7 FE LTE T735 (4GB/64GB) - Hàng Chính Hãng',
      slug: 'may-tinh-bang',
      category: 'Điện tử',
      image: '/product-images/tablet.webp',
      price: '10.390.000',
      shop: 'Tiki Trading',
      shopRating: '4.6',
      shopFollows: '378k+',
      shopIcon: '/pdp-images/tikitrading.png',
      shopReviewsNum: '4.4tr',
      discount: '10.200.000',
      rating: 5,
      numReviews: 42,
      sold: 112,
    },
    {
      name: 'Máy Xay Thịt 2 Lưỡi Kép Nonostyle (2L) - Hàng Chính Hãng',
      slug: 'may-xay-tinh',
      category: 'Điện tử',
      image: '/product-images/mayxaythit.webp',
      price: '275.000',
      shop: 'Tiki Trading',
      shopRating: '4.6',
      shopFollows: '378k+',
      shopIcon: '/pdp-images/tikitrading.png',
      shopReviewsNum: '4.4tr',
      discount: '70.000',
      rating: 5,
      numReviews: 1894,
      sold: '1000+',
    },
    {
      name: 'Balo công sở, đi làm nam nữ GuBag, dòng balo doanh nhân cao cấp, đẹp xịn, chống nước, chống sốc',
      slug: 'balo-cong-so-di-lam-nam-nu-gubag-dong-balo-doanh-nhanh-cao-cap-dep-xin-chong-nuoc-chong-soc',
      category: 'Balo, túi sách',
      image: '/product-images/balo.webp',
      price: '439.000',
      shop: 'GuBag Official Store',
      shopRating: '4.6',
      shopFollows: '261',
      shopIcon: '/pdp-images/gubag.png',
      shopReviewsNum: '1k',
      discount: '430.000',
      rating: 5,
      numReviews: 95,
      sold: 210,
    },
    {
      name: 'Dây nịch Huy Hoàng da bò vân cá sấu nhiều màu sắc',
      slug: 'day-nich-huy-hoang-da-bo-van-ca-sau-nhieu-mau-sac',
      category: 'Quần áo',
      image: '/product-images/daynich.webp',
      price: '559.000',
      shop: 'HuyHoang Shop',
      shopRating: '4.5',
      shopFollows: '93',
      shopIcon: '/pdp-images/huyhoang.png',
      shopReviewsNum: '908',
      discount: '540.000',
      rating: 3,
      numReviews: 5,
      sold: 20,
    },
    {
      name: 'NHẬP KHẨU USA CHÍNH HÃNG - Viên uống ngừa loãng xương, hỗ trợ sức khỏe xương khớp Solgar Vitamin D3 1000 IU',
      slug: 'nhap-khau-usa-chinh-hang-vien-uong-ngua-loang-xuong',
      category: 'Thực phẩm chức năng',
      image: '/product-images/nhansam.webp',
      price: '461.000',
      shop: 'Solgar Official Store',
      shopRating: '4.7',
      shopFollows: '313',
      shopIcon: '/pdp-images/solgar.png',
      shopReviewsNum: '190',
      discount: '450.000',
      rating: 5,
      numReviews: 13,
      sold: 47,
    },
    {
      name: 'Tay Cầm PlayStation PS4 Sony Dualshock 4 (Màu Xanh Đen) - Hàng Chính Hãng',
      slug: 'tay-cam-playstation-ps4-sony-dualshock-4-mau-xanh-den-hang-chinh-hang',
      category: 'Điện tử',
      image: '/product-images/ps4.webp',
      price: '1.189.000',
      shop: 'Bách Tung PS',
      shopRating: '4.7',
      shopFollows: '240',
      shopIcon: '/pdp-images/bachtung.png',
      shopReviewsNum: '507',
      discount: '1.150.000',
      rating: 5,
      numReviews: 7,
      sold: 15,
    },
    {
      name: 'VGA GIGABYTE GTX 1050 Ti Windforce OC 4G -Hàng chính hãng',
      slug: 'vga-gigabyte-gtx-1050-ti-windforce-oc-4g-hang-chinh-hang',
      category: 'Điện tử',
      image: '/product-images/vga.webp',
      price: '5.500.000',
      shop: 'Bách Tung PS',
      shopRating: '4.7',
      shopFollows: '240',
      shopIcon: '/pdp-images/bachtung.png',
      shopReviewsNum: '507',
      discount: '5.450.000',
      rating: 4,
      numReviews: 5,
      sold: 11,
    },
    {
      name: 'Khẩu Trang 3D (10 chiếc), Khẩu Trang 4D KF94 Họa Tiết Thời Trang, Khung Vòm 4D Chống Trôi Son, Dùng Một Lần',
      slug: 'khau-trang-3d-10-chiec-khau-trang-4d-kf94-hoa-tiet-thoi-trang-khung-vom-4d-chong-troi-son-dung-mot-lan',
      category: 'Quần áo',
      image: '/product-images/khautrang.webp',
      price: '9000',
      shop: 'VSeat',
      shopRating: '4.8',
      shopFollows: '279',
      shopIcon: '/pdp-images/vseat.jpg',
      shopReviewsNum: '481',
      discount: '8000',
      rating: 5,
      numReviews: 101,
      sold: '1000+',
    },
    {
      name: 'Bộ Ga và Vỏ Gối Akemi Uchi Tencel Melville Mont, 5 món',
      slug: 'bo-ga-va-vo-goi-akemi-uchi-tencel-melville-mont-5-mon',
      category: 'stuff',
      image: '/product-images/gagiuong.webp',
      price: '2.006.000',
      shop: 'Akemi Official Store',
      shopRating: '4.7',
      shopFollows: '400',
      shopIcon: '/pdp-images/akemi.png',
      shopReviewsNum: '74',
      discount: '2.000.000',
      rating: 4,
      numReviews: 2,
      sold: 11,
    },
    {
      name: 'Bàn Gấp Học Sinh Thông Minh Gấp Gọn, Bàn Xếp Laptop Đa Năng Có Thể Gấp Gọn Tùy Chỉnh Nhiều Góc Độ. Chất Liệu Trúc Siêu Nhẹ - Hàng Chính Hãng Tamayoko TM02',
      slug: 'ban-gap-hoc-sinh',
      category: 'stuff',
      image: '/product-images/bangap.webp',
      price: '399.000',
      shop: 'Future Store',
      shopRating: '4.6',
      shopFollows: '2.2k',
      shopIcon: '/pdp-images/future.png',
      shopReviewsNum: '19k',
      discount: '300.000',
      rating: 4,
      numReviews: 301,
      sold: 908,
    },
    {
      name: 'Màn Hình Cong 1500R Gaming Gigabyte G27FC 27" FullHD (1920x1080) 1ms 165Hz VA Cong Stereo Speaker (2W x 2) - Hàng Chính Hãng',
      slug: 'man-hinh-cong-1550r-gaming-gigabyte',
      category: 'Điện tử',
      image: '/product-images/manhinh.webp',
      price: '5.390.000',
      shop: 'Vi Tinh Chi Cuong',
      shopRating: '4.7',
      shopFollows: '511',
      shopIcon: '/pdp-images/vitinhchicuong.png',
      shopReviewsNum: '2.1k',
      discount: '5.300.000',
      rating: 4,
      numReviews: 1,
      sold: 4,
    },
    {
      name: 'Điện Thoại iPhone 13 Pro Max 128GB - Hàng Chính Hãng',
      slug: 'dien-thoai-iphone-13-pro-max-128gb-hang-chinh-hang',
      category: 'Điện tử',
      image: '/product-images/iphone13.webp',
      price: '29.990.000',
      shop: 'Tiki Trading',
      shopRating: '4.6',
      shopFollows: '378k+',
      shopIcon: '/pdp-images/tikitrading.png',
      shopReviewsNum: '4.4tr',
      discount: '29.600.000',
      rating: 5,
      numReviews: 514,
      sold: '1000+',
    },
    {
      name: 'Tai Nghe Bluetooth Chụp Tai Sony WH-1000XM4 Hi-Res Noise Canceling - Hàng Chính Hãng',
      slug: 'tai-nghe-bluetooth',
      category: 'Điện tử',
      image: '/product-images/tainghe.webp',
      price: '5.790.000',
      shop: 'Happystores',
      shopRating: '4.6',
      shopFollows: '798',
      shopIcon: '/pdp-images/happystores.png',
      shopReviewsNum: '3.1k',
      discount: '5.600.000',
      rating: 5,
      numReviews: 211,
      sold: 406,
    },
    {
      name: 'Bảng Treo Đồ Nghề Pegboard Cơ Khí SMLIFE WB3 Lưu Trữ Trưng Bày Dụng Cụ Sửa Chữa Thông Minh Dễ Tìm Kiếm',
      slug: 'bang-treo-do-nghe',
      category: 'Dụng cụ cơ khí',
      image: '/product-images/donghe.webp',
      price: '2.169.000',
      shop: 'SMLIFE',
      shopRating: '4.5',
      shopFollows: '850',
      shopIcon: '/pdp-images/smlife.jpg',
      shopReviewsNum: '708',
      discount: '2.100.000',
      rating: 5,
      numReviews: 2,
      sold: 5,
    },
  ],
  products4: [
    {
      name: 'Bộ Ga và Vỏ Gối Akemi Uchi Tencel Melville Mont, 5 món',
      slug: 'bo-ga-va-vo-goi-akemi-uchi-tencel-melville-mont-5-mon',
      category: 'stuff',
      image: '/product-images/gagiuong.webp',
      price: '2.006.000',
      shop: 'Akemi Official Store',
      shopRating: '4.7',
      shopFollows: '400',
      shopIcon: '/pdp-images/akemi.png',
      shopReviewsNum: '74',
      discount: '2.000.000',
      rating: 4,
      numReviews: 2,
      sold: 11,
    },
    {
      name: 'Bàn Gấp Học Sinh Thông Minh Gấp Gọn, Bàn Xếp Laptop Đa Năng Có Thể Gấp Gọn Tùy Chỉnh Nhiều Góc Độ. Chất Liệu Trúc Siêu Nhẹ - Hàng Chính Hãng Tamayoko TM02',
      slug: 'ban-gap-hoc-sinh',
      category: 'stuff',
      image: '/product-images/bangap.webp',
      price: '399.000',
      shop: 'Future Store',
      shopRating: '4.6',
      shopFollows: '2.2k',
      shopIcon: '/pdp-images/future.png',
      shopReviewsNum: '19k',
      discount: '300.000',
      rating: 4,
      numReviews: 301,
      sold: 908,
    },
    {
      name: 'Màn Hình Cong 1500R Gaming Gigabyte G27FC 27" FullHD (1920x1080) 1ms 165Hz VA Cong Stereo Speaker (2W x 2) - Hàng Chính Hãng',
      slug: 'man-hinh-cong-1550r-gaming-gigabyte',
      category: 'Điện tử',
      image: '/product-images/manhinh.webp',
      price: '5.390.000',
      shop: 'Vi Tinh Chi Cuong',
      shopRating: '4.7',
      shopFollows: '511',
      shopIcon: '/pdp-images/vitinhchicuong.png',
      shopReviewsNum: '2.1k',
      discount: '5.300.000',
      rating: 4,
      numReviews: 1,
      sold: 4,
    },
    {
      name: 'Điện Thoại iPhone 13 Pro Max 128GB - Hàng Chính Hãng',
      slug: 'dien-thoai-iphone-13-pro-max-128gb-hang-chinh-hang',
      category: 'Điện tử',
      image: '/product-images/iphone13.webp',
      price: '29.990.000',
      shop: 'Tiki Trading',
      shopRating: '4.6',
      shopFollows: '378k+',
      shopIcon: '/pdp-images/tikitrading.png',
      shopReviewsNum: '4.4tr',
      discount: '29.600.000',
      rating: 5,
      numReviews: 514,
      sold: '1000+',
    },
    {
      name: 'Tai Nghe Bluetooth Chụp Tai Sony WH-1000XM4 Hi-Res Noise Canceling - Hàng Chính Hãng',
      slug: 'tai-nghe-bluetooth',
      category: 'Điện tử',
      image: '/product-images/tainghe.webp',
      price: '5.790.000',
      shop: 'Happystores',
      shopRating: '4.6',
      shopFollows: '798',
      shopIcon: '/pdp-images/happystores.png',
      shopReviewsNum: '3.1k',
      discount: '5.600.000',
      rating: 5,
      numReviews: 211,
      sold: 406,
    },
    {
      name: 'Bảng Treo Đồ Nghề Pegboard Cơ Khí SMLIFE WB3 Lưu Trữ Trưng Bày Dụng Cụ Sửa Chữa Thông Minh Dễ Tìm Kiếm',
      slug: 'bang-treo-do-nghe',
      category: 'Dụng cụ cơ khí',
      image: '/product-images/donghe.webp',
      price: '2.169.000',
      shop: 'SMLIFE',
      shopRating: '4.5',
      shopFollows: '850',
      shopIcon: '/pdp-images/smlife.jpg',
      shopReviewsNum: '708',
      discount: '2.100.000',
      rating: 5,
      numReviews: 2,
      sold: 5,
    },
    {
      name: 'Cây Cam Ngọt Của Tôi',
      slug: 'cay-cam-ngot-cua-toi',
      category: 'Sách',
      image: '/product-images/caycamngot.webp',
      price: '77.000',
      shop: 'Tiki Trading',
      shopRating: '4.6',
      shopFollows: '378k+',
      shopIcon: '/pdp-images/tikitrading.png',
      shopReviewsNum: '4.4tr',
      discount: '70.000',
      rating: 5,
      numReviews: 8352,
      sold: '1000+',
    },
    {
      name: 'Bộ Ga và Vỏ Gối Akemi Cotton Select Affinity gồm 5 món',
      slug: 'bo-ga-va-vo-goi-akemi-cotton',
      category: 'Nhà cửa',
      image: '/product-images/gagiuong2.webp',
      price: '1.526.000',
      shop: 'Akemi Official Store',
      shopRating: '4.7',
      shopFollows: '400',
      shopIcon: '/pdp-images/akemi.png',
      shopReviewsNum: '74',
      discount: '1.500.000',
      rating: 5,
      numReviews: 5,
      sold: 17,
    },
    {
      name: 'Nồi áp suất điện đa năng Tefal CY601868 - 6 Lít - 15 chức năng - Hàng chính hãng',
      slug: 'noi-ap-suat-dien-da-nang-tefal',
      category: 'Điện tử',
      image: '/product-images/noiapsuat.webp',
      price: '1.667.000',
      shop: 'Mỏ Vàng HCM',
      shopRating: '4.6',
      shopFollows: '1k+',
      shopIcon: '/pdp-images/movang.png',
      shopReviewsNum: '1k',
      discount: '1.640.000',
      rating: 3,
      numReviews: 1,
      sold: 3,
    },
    {
      name: 'Smart Tivi Sony Full HD 50 inch KDL-50W660G/Z',
      slug: 'smart-tivi-sony',
      category: 'Điện tử',
      image: '/product-images/smarttivi.webp',
      price: '12.288.000',
      shop: 'Tiki Trading',
      shopRating: '4.6',
      shopFollows: '378k+',
      shopIcon: '/pdp-images/tikitrading.png',
      shopReviewsNum: '4.4tr',
      discount: '12.200.000',
      rating: 5,
      numReviews: 68,
      sold: 229,
    },
    {
      name: 'Combo Chảo chiên Tefal Natura B2260295 20cm & Chảo chiên sâu lòng Tefal Natura B2266495 24cm - Dùng được trên bếp gas/ bếp hồng ngoại - Công nghệ báo nhiệt thông minh - Hàng chính hãng',
      slug: 'combo-chao-choen',
      category: 'Gia dụng',
      image: '/product-images/combochao.webp',
      price: '399.000',
      shop: 'Tefal Official Store',
      shopRating: '4.6',
      shopFollows: '19k+',
      shopIcon: '/pdp-images/tefal.png',
      shopReviewsNum: '20k',
      discount: '359.000',
      rating: 5,
      numReviews: 844,
      sold: '1000+',
    },
    {
      name: 'Bộ Cây Lau Nhà Tự Vắt Thông Minh 2 Ngăn Parroti Pro PR01 Cao Cấp - Lau Sạch Khô Nhanh – 3 Miếng Lau Microfiber',
      slug: 'cay-lau-nha',
      category: 'Gia dụng',
      image: '/product-images/caylaunha.webp',
      price: '499.000',
      shop: 'Parroti Store',
      shopRating: '4.8',
      shopFollows: '4.6k+',
      shopIcon: '/pdp-images/parroti.png',
      shopReviewsNum: '10k',
      discount: '399.000',
      rating: 5,
      numReviews: 2789,
      sold: '1000+',
    },
    {
      name: 'Đồng hồ thể thao nam nữ AT111',
      slug: 'dong-ho-the-thao',
      category: 'Điện tử',
      image: '/product-images/donghothethao.webp',
      price: '18.000',
      shop: 'Thien Hoang Store',
      shopRating: '4.1',
      shopFollows: '341',
      shopIcon: '/pdp-images/thienhoang.png',
      shopReviewsNum: '256',
      discount: '15.000',
      rating: 3,
      numReviews: 4,
      sold: 13,
    },
    {
      name: 'Chú Thuật Hồi Chiến: Trường Chuyên Chú Thuật Tokyo - Tập 0',
      slug: 'chu-thuat-hoi-chien',
      category: 'Sách',
      image: '/product-images/chuthuat.webp',
      price: '27.300',
      shop: 'Tiki Trading',
      shopRating: '4.6',
      shopFollows: '378k+',
      shopIcon: '/pdp-images/tikitrading.png',
      shopReviewsNum: '4.4tr',
      discount: '25.000',
      rating: 5,
      numReviews: 617,
      sold: '1000+',
    },
    {
      name: 'Cho Tôi Xin Một Vé Đi Tuổi Thơ (Phiên Bản Đặc Biệt)',
      slug: 'cho-toi-xin-mot-ve-di-tuoi-tho',
      category: 'Sách',
      image: '/product-images/chotoimotve.webp',
      price: '278.500',
      shop: 'Tiki Trading',
      shopRating: '4.6',
      shopFollows: '378k+',
      shopIcon: '/pdp-images/tikitrading.png',
      shopReviewsNum: '4.4tr',
      discount: '260.000',
      rating: 5,
      numReviews: 112,
      sold: 375,
    },
    {
      name: 'Pin Panasonic CR 2032 - Hàng chính hãng',
      slug: 'pin-panasonic-cr-2032',
      category: 'Điện tử',
      image: '/product-images/pin.webp',
      price: '50.000',
      shop: 'Thegioipin88',
      shopRating: '4.7',
      shopFollows: '133',
      shopIcon: '/pdp-images/thegioipin.png',
      shopReviewsNum: '2.3k',
      discount: '45.000',
      rating: 4,
      numReviews: 40,
      sold: 624,
    },
    {
      name: 'Máy Tính Bảng Samsung Galaxy Tab S7 FE LTE T735 (4GB/64GB) - Hàng Chính Hãng',
      slug: 'may-tinh-bang',
      category: 'Điện tử',
      image: '/product-images/tablet.webp',
      price: '10.390.000',
      shop: 'Tiki Trading',
      shopRating: '4.6',
      shopFollows: '378k+',
      shopIcon: '/pdp-images/tikitrading.png',
      shopReviewsNum: '4.4tr',
      discount: '10.200.000',
      rating: 5,
      numReviews: 42,
      sold: 112,
    },
    {
      name: 'Máy Xay Thịt 2 Lưỡi Kép Nonostyle (2L) - Hàng Chính Hãng',
      slug: 'may-xay-tinh',
      category: 'Điện tử',
      image: '/product-images/mayxaythit.webp',
      price: '275.000',
      shop: 'Tiki Trading',
      shopRating: '4.6',
      shopFollows: '378k+',
      shopIcon: '/pdp-images/tikitrading.png',
      shopReviewsNum: '4.4tr',
      discount: '70.000',
      rating: 5,
      numReviews: 1894,
      sold: '1000+',
    },
    {
      name: 'Balo công sở, đi làm nam nữ GuBag, dòng balo doanh nhân cao cấp, đẹp xịn, chống nước, chống sốc',
      slug: 'balo-cong-so-di-lam-nam-nu-gubag-dong-balo-doanh-nhanh-cao-cap-dep-xin-chong-nuoc-chong-soc',
      category: 'Balo, túi sách',
      image: '/product-images/balo.webp',
      price: '439.000',
      shop: 'GuBag Official Store',
      shopRating: '4.6',
      shopFollows: '261',
      shopIcon: '/pdp-images/gubag.png',
      shopReviewsNum: '1k',
      discount: '430.000',
      rating: 5,
      numReviews: 95,
      sold: 210,
    },
    {
      name: 'Dây nịch Huy Hoàng da bò vân cá sấu nhiều màu sắc',
      slug: 'day-nich-huy-hoang-da-bo-van-ca-sau-nhieu-mau-sac',
      category: 'Quần áo',
      image: '/product-images/daynich.webp',
      price: '559.000',
      shop: 'HuyHoang Shop',
      shopRating: '4.5',
      shopFollows: '93',
      shopIcon: '/pdp-images/huyhoang.png',
      shopReviewsNum: '908',
      discount: '540.000',
      rating: 3,
      numReviews: 5,
      sold: 20,
    },
    {
      name: 'NHẬP KHẨU USA CHÍNH HÃNG - Viên uống ngừa loãng xương, hỗ trợ sức khỏe xương khớp Solgar Vitamin D3 1000 IU',
      slug: 'nhap-khau-usa-chinh-hang-vien-uong-ngua-loang-xuong',
      category: 'Thực phẩm chức năng',
      image: '/product-images/nhansam.webp',
      price: '461.000',
      shop: 'Solgar Official Store',
      shopRating: '4.7',
      shopFollows: '313',
      shopIcon: '/pdp-images/solgar.png',
      shopReviewsNum: '190',
      discount: '450.000',
      rating: 5,
      numReviews: 13,
      sold: 47,
    },
    {
      name: 'Tay Cầm PlayStation PS4 Sony Dualshock 4 (Màu Xanh Đen) - Hàng Chính Hãng',
      slug: 'tay-cam-playstation-ps4-sony-dualshock-4-mau-xanh-den-hang-chinh-hang',
      category: 'Điện tử',
      image: '/product-images/ps4.webp',
      price: '1.189.000',
      shop: 'Bách Tung PS',
      shopRating: '4.7',
      shopFollows: '240',
      shopIcon: '/pdp-images/bachtung.png',
      shopReviewsNum: '507',
      discount: '1.150.000',
      rating: 5,
      numReviews: 7,
      sold: 15,
    },
    {
      name: 'VGA GIGABYTE GTX 1050 Ti Windforce OC 4G -Hàng chính hãng',
      slug: 'vga-gigabyte-gtx-1050-ti-windforce-oc-4g-hang-chinh-hang',
      category: 'Điện tử',
      image: '/product-images/vga.webp',
      price: '5.500.000',
      shop: 'Bách Tung PS',
      shopRating: '4.7',
      shopFollows: '240',
      shopIcon: '/pdp-images/bachtung.png',
      shopReviewsNum: '507',
      discount: '5.450.000',
      rating: 4,
      numReviews: 5,
      sold: 11,
    },
    {
      name: 'Khẩu Trang 3D (10 chiếc), Khẩu Trang 4D KF94 Họa Tiết Thời Trang, Khung Vòm 4D Chống Trôi Son, Dùng Một Lần',
      slug: 'khau-trang-3d-10-chiec-khau-trang-4d-kf94-hoa-tiet-thoi-trang-khung-vom-4d-chong-troi-son-dung-mot-lan',
      category: 'Quần áo',
      image: '/product-images/khautrang.webp',
      price: '9000',
      shop: 'VSeat',
      shopRating: '4.8',
      shopFollows: '279',
      shopIcon: '/pdp-images/vseat.jpg',
      shopReviewsNum: '481',
      discount: '8000',
      rating: 5,
      numReviews: 101,
      sold: '1000+',
    },
  ],
  products5: [
    {
      name: 'Đồng hồ thể thao nam nữ AT111',
      slug: 'dong-ho-the-thao',
      category: 'Điện tử',
      image: '/product-images/donghothethao.webp',
      price: '18.000',
      shop: 'Thien Hoang Store',
      shopRating: '4.1',
      shopFollows: '341',
      shopIcon: '/pdp-images/thienhoang.png',
      shopReviewsNum: '256',
      discount: '15.000',
      rating: 3,
      numReviews: 4,
      sold: 13,
    },
    {
      name: 'Chú Thuật Hồi Chiến: Trường Chuyên Chú Thuật Tokyo - Tập 0',
      slug: 'chu-thuat-hoi-chien',
      category: 'Sách',
      image: '/product-images/chuthuat.webp',
      price: '27.300',
      shop: 'Tiki Trading',
      shopRating: '4.6',
      shopFollows: '378k+',
      shopIcon: '/pdp-images/tikitrading.png',
      shopReviewsNum: '4.4tr',
      discount: '25.000',
      rating: 5,
      numReviews: 617,
      sold: '1000+',
    },
    {
      name: 'Cho Tôi Xin Một Vé Đi Tuổi Thơ (Phiên Bản Đặc Biệt)',
      slug: 'cho-toi-xin-mot-ve-di-tuoi-tho',
      category: 'Sách',
      image: '/product-images/chotoimotve.webp',
      price: '278.500',
      shop: 'Tiki Trading',
      shopRating: '4.6',
      shopFollows: '378k+',
      shopIcon: '/pdp-images/tikitrading.png',
      shopReviewsNum: '4.4tr',
      discount: '260.000',
      rating: 5,
      numReviews: 112,
      sold: 375,
    },
    {
      name: 'Pin Panasonic CR 2032 - Hàng chính hãng',
      slug: 'pin-panasonic-cr-2032',
      category: 'Điện tử',
      image: '/product-images/pin.webp',
      price: '50.000',
      shop: 'Thegioipin88',
      shopRating: '4.7',
      shopFollows: '133',
      shopIcon: '/pdp-images/thegioipin.png',
      shopReviewsNum: '2.3k',
      discount: '45.000',
      rating: 4,
      numReviews: 40,
      sold: 624,
    },
    {
      name: 'Máy Tính Bảng Samsung Galaxy Tab S7 FE LTE T735 (4GB/64GB) - Hàng Chính Hãng',
      slug: 'may-tinh-bang',
      category: 'Điện tử',
      image: '/product-images/tablet.webp',
      price: '10.390.000',
      shop: 'Tiki Trading',
      shopRating: '4.6',
      shopFollows: '378k+',
      shopIcon: '/pdp-images/tikitrading.png',
      shopReviewsNum: '4.4tr',
      discount: '10.200.000',
      rating: 5,
      numReviews: 42,
      sold: 112,
    },
    {
      name: 'Máy Xay Thịt 2 Lưỡi Kép Nonostyle (2L) - Hàng Chính Hãng',
      slug: 'may-xay-tinh',
      category: 'Điện tử',
      image: '/product-images/mayxaythit.webp',
      price: '275.000',
      shop: 'Tiki Trading',
      shopRating: '4.6',
      shopFollows: '378k+',
      shopIcon: '/pdp-images/tikitrading.png',
      shopReviewsNum: '4.4tr',
      discount: '70.000',
      rating: 5,
      numReviews: 1894,
      sold: '1000+',
    },
    {
      name: 'Cây Cam Ngọt Của Tôi',
      slug: 'cay-cam-ngot-cua-toi',
      category: 'Sách',
      image: '/product-images/caycamngot.webp',
      price: '77.000',
      shop: 'Tiki Trading',
      shopRating: '4.6',
      shopFollows: '378k+',
      shopIcon: '/pdp-images/tikitrading.png',
      shopReviewsNum: '4.4tr',
      discount: '70.000',
      rating: 5,
      numReviews: 8352,
      sold: '1000+',
    },
    {
      name: 'Bộ Ga và Vỏ Gối Akemi Cotton Select Affinity gồm 5 món',
      slug: 'bo-ga-va-vo-goi-akemi-cotton',
      category: 'Nhà cửa',
      image: '/product-images/gagiuong2.webp',
      price: '1.526.000',
      shop: 'Akemi Official Store',
      shopRating: '4.7',
      shopFollows: '400',
      shopIcon: '/pdp-images/akemi.png',
      shopReviewsNum: '74',
      discount: '1.500.000',
      rating: 5,
      numReviews: 5,
      sold: 17,
    },
    {
      name: 'Nồi áp suất điện đa năng Tefal CY601868 - 6 Lít - 15 chức năng - Hàng chính hãng',
      slug: 'noi-ap-suat-dien-da-nang-tefal',
      category: 'Điện tử',
      image: '/product-images/noiapsuat.webp',
      price: '1.667.000',
      shop: 'Mỏ Vàng HCM',
      shopRating: '4.6',
      shopFollows: '1k+',
      shopIcon: '/pdp-images/movang.png',
      shopReviewsNum: '1k',
      discount: '1.640.000',
      rating: 3,
      numReviews: 1,
      sold: 3,
    },
    {
      name: 'Smart Tivi Sony Full HD 50 inch KDL-50W660G/Z',
      slug: 'smart-tivi-sony',
      category: 'Điện tử',
      image: '/product-images/smarttivi.webp',
      price: '12.288.000',
      shop: 'Tiki Trading',
      shopRating: '4.6',
      shopFollows: '378k+',
      shopIcon: '/pdp-images/tikitrading.png',
      shopReviewsNum: '4.4tr',
      discount: '12.200.000',
      rating: 5,
      numReviews: 68,
      sold: 229,
    },
    {
      name: 'Combo Chảo chiên Tefal Natura B2260295 20cm & Chảo chiên sâu lòng Tefal Natura B2266495 24cm - Dùng được trên bếp gas/ bếp hồng ngoại - Công nghệ báo nhiệt thông minh - Hàng chính hãng',
      slug: 'combo-chao-choen',
      category: 'Gia dụng',
      image: '/product-images/combochao.webp',
      price: '399.000',
      shop: 'Tefal Official Store',
      shopRating: '4.6',
      shopFollows: '19k+',
      shopIcon: '/pdp-images/tefal.png',
      shopReviewsNum: '20k',
      discount: '359.000',
      rating: 5,
      numReviews: 844,
      sold: '1000+',
    },
    {
      name: 'Bộ Cây Lau Nhà Tự Vắt Thông Minh 2 Ngăn Parroti Pro PR01 Cao Cấp - Lau Sạch Khô Nhanh – 3 Miếng Lau Microfiber',
      slug: 'cay-lau-nha',
      category: 'Gia dụng',
      image: '/product-images/caylaunha.webp',
      price: '499.000',
      shop: 'Parroti Store',
      shopRating: '4.8',
      shopFollows: '4.6k+',
      shopIcon: '/pdp-images/parroti.png',
      shopReviewsNum: '10k',
      discount: '399.000',
      rating: 5,
      numReviews: 2789,
      sold: '1000+',
    },
    {
      name: 'Bộ Ga và Vỏ Gối Akemi Uchi Tencel Melville Mont, 5 món',
      slug: 'bo-ga-va-vo-goi-akemi-uchi-tencel-melville-mont-5-mon',
      category: 'stuff',
      image: '/product-images/gagiuong.webp',
      price: '2.006.000',
      shop: 'Akemi Official Store',
      shopRating: '4.7',
      shopFollows: '400',
      shopIcon: '/pdp-images/akemi.png',
      shopReviewsNum: '74',
      discount: '2.000.000',
      rating: 4,
      numReviews: 2,
      sold: 11,
    },
    {
      name: 'Bàn Gấp Học Sinh Thông Minh Gấp Gọn, Bàn Xếp Laptop Đa Năng Có Thể Gấp Gọn Tùy Chỉnh Nhiều Góc Độ. Chất Liệu Trúc Siêu Nhẹ - Hàng Chính Hãng Tamayoko TM02',
      slug: 'ban-gap-hoc-sinh',
      category: 'stuff',
      image: '/product-images/bangap.webp',
      price: '399.000',
      shop: 'Future Store',
      shopRating: '4.6',
      shopFollows: '2.2k',
      shopIcon: '/pdp-images/future.png',
      shopReviewsNum: '19k',
      discount: '300.000',
      rating: 4,
      numReviews: 301,
      sold: 908,
    },
    {
      name: 'Màn Hình Cong 1500R Gaming Gigabyte G27FC 27" FullHD (1920x1080) 1ms 165Hz VA Cong Stereo Speaker (2W x 2) - Hàng Chính Hãng',
      slug: 'man-hinh-cong-1550r-gaming-gigabyte',
      category: 'Điện tử',
      image: '/product-images/manhinh.webp',
      price: '5.390.000',
      shop: 'Vi Tinh Chi Cuong',
      shopRating: '4.7',
      shopFollows: '511',
      shopIcon: '/pdp-images/vitinhchicuong.png',
      shopReviewsNum: '2.1k',
      discount: '5.300.000',
      rating: 4,
      numReviews: 1,
      sold: 4,
    },
    {
      name: 'Điện Thoại iPhone 13 Pro Max 128GB - Hàng Chính Hãng',
      slug: 'dien-thoai-iphone-13-pro-max-128gb-hang-chinh-hang',
      category: 'Điện tử',
      image: '/product-images/iphone13.webp',
      price: '29.990.000',
      shop: 'Tiki Trading',
      shopRating: '4.6',
      shopFollows: '378k+',
      shopIcon: '/pdp-images/tikitrading.png',
      shopReviewsNum: '4.4tr',
      discount: '29.600.000',
      rating: 5,
      numReviews: 514,
      sold: '1000+',
    },
    {
      name: 'Tai Nghe Bluetooth Chụp Tai Sony WH-1000XM4 Hi-Res Noise Canceling - Hàng Chính Hãng',
      slug: 'tai-nghe-bluetooth',
      category: 'Điện tử',
      image: '/product-images/tainghe.webp',
      price: '5.790.000',
      shop: 'Happystores',
      shopRating: '4.6',
      shopFollows: '798',
      shopIcon: '/pdp-images/happystores.png',
      shopReviewsNum: '3.1k',
      discount: '5.600.000',
      rating: 5,
      numReviews: 211,
      sold: 406,
    },
    {
      name: 'Bảng Treo Đồ Nghề Pegboard Cơ Khí SMLIFE WB3 Lưu Trữ Trưng Bày Dụng Cụ Sửa Chữa Thông Minh Dễ Tìm Kiếm',
      slug: 'bang-treo-do-nghe',
      category: 'Dụng cụ cơ khí',
      image: '/product-images/donghe.webp',
      price: '2.169.000',
      shop: 'SMLIFE',
      shopRating: '4.5',
      shopFollows: '850',
      shopIcon: '/pdp-images/smlife.jpg',
      shopReviewsNum: '708',
      discount: '2.100.000',
      rating: 5,
      numReviews: 2,
      sold: 5,
    },
    {
      name: 'Balo công sở, đi làm nam nữ GuBag, dòng balo doanh nhân cao cấp, đẹp xịn, chống nước, chống sốc',
      slug: 'balo-cong-so-di-lam-nam-nu-gubag-dong-balo-doanh-nhanh-cao-cap-dep-xin-chong-nuoc-chong-soc',
      category: 'Balo, túi sách',
      image: '/product-images/balo.webp',
      price: '439.000',
      shop: 'GuBag Official Store',
      shopRating: '4.6',
      shopFollows: '261',
      shopIcon: '/pdp-images/gubag.png',
      shopReviewsNum: '1k',
      discount: '430.000',
      rating: 5,
      numReviews: 95,
      sold: 210,
    },
    {
      name: 'Dây nịch Huy Hoàng da bò vân cá sấu nhiều màu sắc',
      slug: 'day-nich-huy-hoang-da-bo-van-ca-sau-nhieu-mau-sac',
      category: 'Quần áo',
      image: '/product-images/daynich.webp',
      price: '559.000',
      shop: 'HuyHoang Shop',
      shopRating: '4.5',
      shopFollows: '93',
      shopIcon: '/pdp-images/huyhoang.png',
      shopReviewsNum: '908',
      discount: '540.000',
      rating: 3,
      numReviews: 5,
      sold: 20,
    },
    {
      name: 'NHẬP KHẨU USA CHÍNH HÃNG - Viên uống ngừa loãng xương, hỗ trợ sức khỏe xương khớp Solgar Vitamin D3 1000 IU',
      slug: 'nhap-khau-usa-chinh-hang-vien-uong-ngua-loang-xuong',
      category: 'Thực phẩm chức năng',
      image: '/product-images/nhansam.webp',
      price: '461.000',
      shop: 'Solgar Official Store',
      shopRating: '4.7',
      shopFollows: '313',
      shopIcon: '/pdp-images/solgar.png',
      shopReviewsNum: '190',
      discount: '450.000',
      rating: 5,
      numReviews: 13,
      sold: 47,
    },
    {
      name: 'Tay Cầm PlayStation PS4 Sony Dualshock 4 (Màu Xanh Đen) - Hàng Chính Hãng',
      slug: 'tay-cam-playstation-ps4-sony-dualshock-4-mau-xanh-den-hang-chinh-hang',
      category: 'Điện tử',
      image: '/product-images/ps4.webp',
      price: '1.189.000',
      shop: 'Bách Tung PS',
      shopRating: '4.7',
      shopFollows: '240',
      shopIcon: '/pdp-images/bachtung.png',
      shopReviewsNum: '507',
      discount: '1.150.000',
      rating: 5,
      numReviews: 7,
      sold: 15,
    },
    {
      name: 'VGA GIGABYTE GTX 1050 Ti Windforce OC 4G -Hàng chính hãng',
      slug: 'vga-gigabyte-gtx-1050-ti-windforce-oc-4g-hang-chinh-hang',
      category: 'Điện tử',
      image: '/product-images/vga.webp',
      price: '5.500.000',
      shop: 'Bách Tung PS',
      shopRating: '4.7',
      shopFollows: '240',
      shopIcon: '/pdp-images/bachtung.png',
      shopReviewsNum: '507',
      discount: '5.450.000',
      rating: 4,
      numReviews: 5,
      sold: 11,
    },
    {
      name: 'Khẩu Trang 3D (10 chiếc), Khẩu Trang 4D KF94 Họa Tiết Thời Trang, Khung Vòm 4D Chống Trôi Son, Dùng Một Lần',
      slug: 'khau-trang-3d-10-chiec-khau-trang-4d-kf94-hoa-tiet-thoi-trang-khung-vom-4d-chong-troi-son-dung-mot-lan',
      category: 'Quần áo',
      image: '/product-images/khautrang.webp',
      price: '9000',
      shop: 'VSeat',
      shopRating: '4.8',
      shopFollows: '279',
      shopIcon: '/pdp-images/vseat.jpg',
      shopReviewsNum: '481',
      discount: '8000',
      rating: 5,
      numReviews: 101,
      sold: '1000+',
    },
  ],
  products6: [
    {
      name: 'Bộ Ga và Vỏ Gối Akemi Uchi Tencel Melville Mont, 5 món',
      slug: 'bo-ga-va-vo-goi-akemi-uchi-tencel-melville-mont-5-mon',
      category: 'stuff',
      image: '/product-images/gagiuong.webp',
      price: '2.006.000',
      shop: 'Akemi Official Store',
      shopRating: '4.7',
      shopFollows: '400',
      shopIcon: '/pdp-images/akemi.png',
      shopReviewsNum: '74',
      discount: '2.000.000',
      rating: 4,
      numReviews: 2,
      sold: 11,
    },
    {
      name: 'Bàn Gấp Học Sinh Thông Minh Gấp Gọn, Bàn Xếp Laptop Đa Năng Có Thể Gấp Gọn Tùy Chỉnh Nhiều Góc Độ. Chất Liệu Trúc Siêu Nhẹ - Hàng Chính Hãng Tamayoko TM02',
      slug: 'ban-gap-hoc-sinh',
      category: 'stuff',
      image: '/product-images/bangap.webp',
      price: '399.000',
      shop: 'Future Store',
      shopRating: '4.6',
      shopFollows: '2.2k',
      shopIcon: '/pdp-images/future.png',
      shopReviewsNum: '19k',
      discount: '300.000',
      rating: 4,
      numReviews: 301,
      sold: 908,
    },
    {
      name: 'Màn Hình Cong 1500R Gaming Gigabyte G27FC 27" FullHD (1920x1080) 1ms 165Hz VA Cong Stereo Speaker (2W x 2) - Hàng Chính Hãng',
      slug: 'man-hinh-cong-1550r-gaming-gigabyte',
      category: 'Điện tử',
      image: '/product-images/manhinh.webp',
      price: '5.390.000',
      shop: 'Vi Tinh Chi Cuong',
      shopRating: '4.7',
      shopFollows: '511',
      shopIcon: '/pdp-images/vitinhchicuong.png',
      shopReviewsNum: '2.1k',
      discount: '5.300.000',
      rating: 4,
      numReviews: 1,
      sold: 4,
    },
    {
      name: 'Điện Thoại iPhone 13 Pro Max 128GB - Hàng Chính Hãng',
      slug: 'dien-thoai-iphone-13-pro-max-128gb-hang-chinh-hang',
      category: 'Điện tử',
      image: '/product-images/iphone13.webp',
      price: '29.990.000',
      shop: 'Tiki Trading',
      shopRating: '4.6',
      shopFollows: '378k+',
      shopIcon: '/pdp-images/tikitrading.png',
      shopReviewsNum: '4.4tr',
      discount: '29.600.000',
      rating: 5,
      numReviews: 514,
      sold: '1000+',
    },
    {
      name: 'Tai Nghe Bluetooth Chụp Tai Sony WH-1000XM4 Hi-Res Noise Canceling - Hàng Chính Hãng',
      slug: 'tai-nghe-bluetooth',
      category: 'Điện tử',
      image: '/product-images/tainghe.webp',
      price: '5.790.000',
      shop: 'Happystores',
      shopRating: '4.6',
      shopFollows: '798',
      shopIcon: '/pdp-images/happystores.png',
      shopReviewsNum: '3.1k',
      discount: '5.600.000',
      rating: 5,
      numReviews: 211,
      sold: 406,
    },
    {
      name: 'Bảng Treo Đồ Nghề Pegboard Cơ Khí SMLIFE WB3 Lưu Trữ Trưng Bày Dụng Cụ Sửa Chữa Thông Minh Dễ Tìm Kiếm',
      slug: 'bang-treo-do-nghe',
      category: 'Dụng cụ cơ khí',
      image: '/product-images/donghe.webp',
      price: '2.169.000',
      shop: 'SMLIFE',
      shopRating: '4.5',
      shopFollows: '850',
      shopIcon: '/pdp-images/smlife.jpg',
      shopReviewsNum: '708',
      discount: '2.100.000',
      rating: 5,
      numReviews: 2,
      sold: 5,
    },
    {
      name: 'Đồng hồ thể thao nam nữ AT111',
      slug: 'dong-ho-the-thao',
      category: 'Điện tử',
      image: '/product-images/donghothethao.webp',
      price: '18.000',
      shop: 'Thien Hoang Store',
      shopRating: '4.1',
      shopFollows: '341',
      shopIcon: '/pdp-images/thienhoang.png',
      shopReviewsNum: '256',
      discount: '15.000',
      rating: 3,
      numReviews: 4,
      sold: 13,
    },
    {
      name: 'Chú Thuật Hồi Chiến: Trường Chuyên Chú Thuật Tokyo - Tập 0',
      slug: 'chu-thuat-hoi-chien',
      category: 'Sách',
      image: '/product-images/chuthuat.webp',
      price: '27.300',
      shop: 'Tiki Trading',
      shopRating: '4.6',
      shopFollows: '378k+',
      shopIcon: '/pdp-images/tikitrading.png',
      shopReviewsNum: '4.4tr',
      discount: '25.000',
      rating: 5,
      numReviews: 617,
      sold: '1000+',
    },
    {
      name: 'Cho Tôi Xin Một Vé Đi Tuổi Thơ (Phiên Bản Đặc Biệt)',
      slug: 'cho-toi-xin-mot-ve-di-tuoi-tho',
      category: 'Sách',
      image: '/product-images/chotoimotve.webp',
      price: '278.500',
      shop: 'Tiki Trading',
      shopRating: '4.6',
      shopFollows: '378k+',
      shopIcon: '/pdp-images/tikitrading.png',
      shopReviewsNum: '4.4tr',
      discount: '260.000',
      rating: 5,
      numReviews: 112,
      sold: 375,
    },
    {
      name: 'Pin Panasonic CR 2032 - Hàng chính hãng',
      slug: 'pin-panasonic-cr-2032',
      category: 'Điện tử',
      image: '/product-images/pin.webp',
      price: '50.000',
      shop: 'Thegioipin88',
      shopRating: '4.7',
      shopFollows: '133',
      shopIcon: '/pdp-images/thegioipin.png',
      shopReviewsNum: '2.3k',
      discount: '45.000',
      rating: 4,
      numReviews: 40,
      sold: 624,
    },
    {
      name: 'Máy Tính Bảng Samsung Galaxy Tab S7 FE LTE T735 (4GB/64GB) - Hàng Chính Hãng',
      slug: 'may-tinh-bang',
      category: 'Điện tử',
      image: '/product-images/tablet.webp',
      price: '10.390.000',
      shop: 'Tiki Trading',
      shopRating: '4.6',
      shopFollows: '378k+',
      shopIcon: '/pdp-images/tikitrading.png',
      shopReviewsNum: '4.4tr',
      discount: '10.200.000',
      rating: 5,
      numReviews: 42,
      sold: 112,
    },
    {
      name: 'Máy Xay Thịt 2 Lưỡi Kép Nonostyle (2L) - Hàng Chính Hãng',
      slug: 'may-xay-tinh',
      category: 'Điện tử',
      image: '/product-images/mayxaythit.webp',
      price: '275.000',
      shop: 'Tiki Trading',
      shopRating: '4.6',
      shopFollows: '378k+',
      shopIcon: '/pdp-images/tikitrading.png',
      shopReviewsNum: '4.4tr',
      discount: '70.000',
      rating: 5,
      numReviews: 1894,
      sold: '1000+',
    },
    {
      name: 'Balo công sở, đi làm nam nữ GuBag, dòng balo doanh nhân cao cấp, đẹp xịn, chống nước, chống sốc',
      slug: 'balo-cong-so-di-lam-nam-nu-gubag-dong-balo-doanh-nhanh-cao-cap-dep-xin-chong-nuoc-chong-soc',
      category: 'Balo, túi sách',
      image: '/product-images/balo.webp',
      price: '439.000',
      shop: 'GuBag Official Store',
      shopRating: '4.6',
      shopFollows: '261',
      shopIcon: '/pdp-images/gubag.png',
      shopReviewsNum: '1k',
      discount: '430.000',
      rating: 5,
      numReviews: 95,
      sold: 210,
    },
    {
      name: 'Dây nịch Huy Hoàng da bò vân cá sấu nhiều màu sắc',
      slug: 'day-nich-huy-hoang-da-bo-van-ca-sau-nhieu-mau-sac',
      category: 'Quần áo',
      image: '/product-images/daynich.webp',
      price: '559.000',
      shop: 'HuyHoang Shop',
      shopRating: '4.5',
      shopFollows: '93',
      shopIcon: '/pdp-images/huyhoang.png',
      shopReviewsNum: '908',
      discount: '540.000',
      rating: 3,
      numReviews: 5,
      sold: 20,
    },
    {
      name: 'NHẬP KHẨU USA CHÍNH HÃNG - Viên uống ngừa loãng xương, hỗ trợ sức khỏe xương khớp Solgar Vitamin D3 1000 IU',
      slug: 'nhap-khau-usa-chinh-hang-vien-uong-ngua-loang-xuong',
      category: 'Thực phẩm chức năng',
      image: '/product-images/nhansam.webp',
      price: '461.000',
      shop: 'Solgar Official Store',
      shopRating: '4.7',
      shopFollows: '313',
      shopIcon: '/pdp-images/solgar.png',
      shopReviewsNum: '190',
      discount: '450.000',
      rating: 5,
      numReviews: 13,
      sold: 47,
    },
    {
      name: 'Tay Cầm PlayStation PS4 Sony Dualshock 4 (Màu Xanh Đen) - Hàng Chính Hãng',
      slug: 'tay-cam-playstation-ps4-sony-dualshock-4-mau-xanh-den-hang-chinh-hang',
      category: 'Điện tử',
      image: '/product-images/ps4.webp',
      price: '1.189.000',
      shop: 'Bách Tung PS',
      shopRating: '4.7',
      shopFollows: '240',
      shopIcon: '/pdp-images/bachtung.png',
      shopReviewsNum: '507',
      discount: '1.150.000',
      rating: 5,
      numReviews: 7,
      sold: 15,
    },
    {
      name: 'VGA GIGABYTE GTX 1050 Ti Windforce OC 4G -Hàng chính hãng',
      slug: 'vga-gigabyte-gtx-1050-ti-windforce-oc-4g-hang-chinh-hang',
      category: 'Điện tử',
      image: '/product-images/vga.webp',
      price: '5.500.000',
      shop: 'Bách Tung PS',
      shopRating: '4.7',
      shopFollows: '240',
      shopIcon: '/pdp-images/bachtung.png',
      shopReviewsNum: '507',
      discount: '5.450.000',
      rating: 4,
      numReviews: 5,
      sold: 11,
    },
    {
      name: 'Khẩu Trang 3D (10 chiếc), Khẩu Trang 4D KF94 Họa Tiết Thời Trang, Khung Vòm 4D Chống Trôi Son, Dùng Một Lần',
      slug: 'khau-trang-3d-10-chiec-khau-trang-4d-kf94-hoa-tiet-thoi-trang-khung-vom-4d-chong-troi-son-dung-mot-lan',
      category: 'Quần áo',
      image: '/product-images/khautrang.webp',
      price: '9000',
      shop: 'VSeat',
      shopRating: '4.8',
      shopFollows: '279',
      shopIcon: '/pdp-images/vseat.jpg',
      shopReviewsNum: '481',
      discount: '8000',
      rating: 5,
      numReviews: 101,
      sold: '1000+',
    },
    {
      name: 'Cây Cam Ngọt Của Tôi',
      slug: 'cay-cam-ngot-cua-toi',
      category: 'Sách',
      image: '/product-images/caycamngot.webp',
      price: '77.000',
      shop: 'Tiki Trading',
      shopRating: '4.6',
      shopFollows: '378k+',
      shopIcon: '/pdp-images/tikitrading.png',
      shopReviewsNum: '4.4tr',
      discount: '70.000',
      rating: 5,
      numReviews: 8352,
      sold: '1000+',
    },
    {
      name: 'Bộ Ga và Vỏ Gối Akemi Cotton Select Affinity gồm 5 món',
      slug: 'bo-ga-va-vo-goi-akemi-cotton',
      category: 'Nhà cửa',
      image: '/product-images/gagiuong2.webp',
      price: '1.526.000',
      shop: 'Akemi Official Store',
      shopRating: '4.7',
      shopFollows: '400',
      shopIcon: '/pdp-images/akemi.png',
      shopReviewsNum: '74',
      discount: '1.500.000',
      rating: 5,
      numReviews: 5,
      sold: 17,
    },
    {
      name: 'Nồi áp suất điện đa năng Tefal CY601868 - 6 Lít - 15 chức năng - Hàng chính hãng',
      slug: 'noi-ap-suat-dien-da-nang-tefal',
      category: 'Điện tử',
      image: '/product-images/noiapsuat.webp',
      price: '1.667.000',
      shop: 'Mỏ Vàng HCM',
      shopRating: '4.6',
      shopFollows: '1k+',
      shopIcon: '/pdp-images/movang.png',
      shopReviewsNum: '1k',
      discount: '1.640.000',
      rating: 3,
      numReviews: 1,
      sold: 3,
    },
    {
      name: 'Smart Tivi Sony Full HD 50 inch KDL-50W660G/Z',
      slug: 'smart-tivi-sony',
      category: 'Điện tử',
      image: '/product-images/smarttivi.webp',
      price: '12.288.000',
      shop: 'Tiki Trading',
      shopRating: '4.6',
      shopFollows: '378k+',
      shopIcon: '/pdp-images/tikitrading.png',
      shopReviewsNum: '4.4tr',
      discount: '12.200.000',
      rating: 5,
      numReviews: 68,
      sold: 229,
    },
    {
      name: 'Combo Chảo chiên Tefal Natura B2260295 20cm & Chảo chiên sâu lòng Tefal Natura B2266495 24cm - Dùng được trên bếp gas/ bếp hồng ngoại - Công nghệ báo nhiệt thông minh - Hàng chính hãng',
      slug: 'combo-chao-choen',
      category: 'Gia dụng',
      image: '/product-images/combochao.webp',
      price: '399.000',
      shop: 'Tefal Official Store',
      shopRating: '4.6',
      shopFollows: '19k+',
      shopIcon: '/pdp-images/tefal.png',
      shopReviewsNum: '20k',
      discount: '359.000',
      rating: 5,
      numReviews: 844,
      sold: '1000+',
    },
    {
      name: 'Bộ Cây Lau Nhà Tự Vắt Thông Minh 2 Ngăn Parroti Pro PR01 Cao Cấp - Lau Sạch Khô Nhanh – 3 Miếng Lau Microfiber',
      slug: 'cay-lau-nha',
      category: 'Gia dụng',
      image: '/product-images/caylaunha.webp',
      price: '499.000',
      shop: 'Parroti Store',
      shopRating: '4.8',
      shopFollows: '4.6k+',
      shopIcon: '/pdp-images/parroti.png',
      shopReviewsNum: '10k',
      discount: '399.000',
      rating: 5,
      numReviews: 2789,
      sold: '1000+',
    },
  ],
  recommend: [
    {
      name: 'Cây Cam Ngọt Của Tôi',
      slug: 'cay-cam-ngot-cua-toi',
      category: 'Sách',
      image: '/product-images/caycamngot.webp',
      price: '77.000',
      shop: 'Tiki Trading',
      shopRating: '4.6',
      shopFollows: '378k+',
      shopIcon: '/pdp-images/tikitrading.png',
      shopReviewsNum: '4.4tr',
      discount: '70.000',
      rating: 5,
      numReviews: 8352,
      sold: '1000+',
    },
    {
      name: 'Bộ Ga và Vỏ Gối Akemi Cotton Select Affinity gồm 5 món',
      slug: 'bo-ga-va-vo-goi-akemi-cotton',
      category: 'Nhà cửa',
      image: '/product-images/gagiuong2.webp',
      price: '1.526.000',
      shop: 'Akemi Official Store',
      shopRating: '4.7',
      shopFollows: '400',
      shopIcon: '/pdp-images/akemi.png',
      shopReviewsNum: '74',
      discount: '1.500.000',
      rating: 5,
      numReviews: 5,
      sold: 17,
    },
    {
      name: 'Nồi áp suất điện đa năng Tefal CY601868 - 6 Lít - 15 chức năng - Hàng chính hãng',
      slug: 'noi-ap-suat-dien-da-nang-tefal',
      category: 'Điện tử',
      image: '/product-images/noiapsuat.webp',
      price: '1.667.000',
      shop: 'Mỏ Vàng HCM',
      shopRating: '4.6',
      shopFollows: '1k+',
      shopIcon: '/pdp-images/movang.png',
      shopReviewsNum: '1k',
      discount: '1.640.000',
      rating: 3,
      numReviews: 1,
      sold: 3,
    },
    {
      name: 'Smart Tivi Sony Full HD 50 inch KDL-50W660G/Z',
      slug: 'smart-tivi-sony',
      category: 'Điện tử',
      image: '/product-images/smarttivi.webp',
      price: '12.288.000',
      shop: 'Tiki Trading',
      shopRating: '4.6',
      shopFollows: '378k+',
      shopIcon: '/pdp-images/tikitrading.png',
      shopReviewsNum: '4.4tr',
      discount: '12.200.000',
      rating: 5,
      numReviews: 68,
      sold: 229,
    },
    {
      name: 'Combo Chảo chiên Tefal Natura B2260295 20cm & Chảo chiên sâu lòng Tefal Natura B2266495 24cm - Dùng được trên bếp gas/ bếp hồng ngoại - Công nghệ báo nhiệt thông minh - Hàng chính hãng',
      slug: 'combo-chao-choen',
      category: 'Gia dụng',
      image: '/product-images/combochao.webp',
      price: '399.000',
      shop: 'Tefal Official Store',
      shopRating: '4.6',
      shopFollows: '19k+',
      shopIcon: '/pdp-images/tefal.png',
      shopReviewsNum: '20k',
      discount: '359.000',
      rating: 5,
      numReviews: 844,
      sold: '1000+',
    },
    {
      name: 'Bộ Cây Lau Nhà Tự Vắt Thông Minh 2 Ngăn Parroti Pro PR01 Cao Cấp - Lau Sạch Khô Nhanh – 3 Miếng Lau Microfiber',
      slug: 'cay-lau-nha',
      category: 'Gia dụng',
      image: '/product-images/caylaunha.webp',
      price: '499.000',
      shop: 'Parroti Store',
      shopRating: '4.8',
      shopFollows: '4.6k+',
      shopIcon: '/pdp-images/parroti.png',
      shopReviewsNum: '10k',
      discount: '399.000',
      rating: 5,
      numReviews: 2789,
      sold: '1000+',
    },
  ],
};
export default data;
